// Generated by Haxe 4.1.5

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Const : global::haxe.lang.Enum {
		
		protected Const(int index) : base(index) {
		}
		
		
		public static global::hscript.Const CInt(int v) {
			return new global::hscript.Const_CInt(v);
		}
		
		
		public static global::hscript.Const CFloat(double f) {
			return new global::hscript.Const_CFloat(f);
		}
		
		
		public static global::hscript.Const CString(string s) {
			return new global::hscript.Const_CString(s);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Const_CInt : global::hscript.Const {
		
		public Const_CInt(int v) : base(0) {
			this.v = v;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "CInt";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.v});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Const_CInt en = ( other as global::hscript.Const_CInt );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CInt", new object[]{this.v});
		}
		
		
		public readonly int v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Const_CFloat : global::hscript.Const {
		
		public Const_CFloat(double f) : base(1) {
			this.f = f;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "CFloat";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Const_CFloat en = ( other as global::hscript.Const_CFloat );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CFloat", new object[]{this.f});
		}
		
		
		public readonly double f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Const_CString : global::hscript.Const {
		
		public Const_CString(string s) : base(2) {
			this.s = s;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.s});
		}
		
		
		public override string getTag() {
			return "CString";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(2, new object[]{this.s});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Const_CString en = ( other as global::hscript.Const_CString );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.s) ), ((object) (en.s) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CString", new object[]{this.s});
		}
		
		
		public readonly string s;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Expr : global::haxe.lang.Enum {
		
		protected Expr(int index) : base(index) {
		}
		
		
		public static global::hscript.Expr EConst(global::hscript.Const c) {
			return new global::hscript.Expr_EConst(c);
		}
		
		
		public static global::hscript.Expr EIdent(string v) {
			return new global::hscript.Expr_EIdent(v);
		}
		
		
		public static global::hscript.Expr EVar(string n, global::hscript.CType t, global::hscript.Expr e) {
			return new global::hscript.Expr_EVar(n, t, e);
		}
		
		
		public static global::hscript.Expr EParent(global::hscript.Expr e) {
			return new global::hscript.Expr_EParent(e);
		}
		
		
		public static global::hscript.Expr EBlock(global::Array<object> e) {
			return new global::hscript.Expr_EBlock(e);
		}
		
		
		public static global::hscript.Expr EField(global::hscript.Expr e, string f) {
			return new global::hscript.Expr_EField(e, f);
		}
		
		
		public static global::hscript.Expr EBinop(string op, global::hscript.Expr e1, global::hscript.Expr e2) {
			return new global::hscript.Expr_EBinop(op, e1, e2);
		}
		
		
		public static global::hscript.Expr EUnop(string op, bool prefix, global::hscript.Expr e) {
			return new global::hscript.Expr_EUnop(op, prefix, e);
		}
		
		
		public static global::hscript.Expr ECall(global::hscript.Expr e, global::Array<object> @params) {
			return new global::hscript.Expr_ECall(e, @params);
		}
		
		
		public static global::hscript.Expr EIf(global::hscript.Expr cond, global::hscript.Expr e1, global::hscript.Expr e2) {
			return new global::hscript.Expr_EIf(cond, e1, e2);
		}
		
		
		public static global::hscript.Expr EWhile(global::hscript.Expr cond, global::hscript.Expr e) {
			return new global::hscript.Expr_EWhile(cond, e);
		}
		
		
		public static global::hscript.Expr EFor(string v, global::hscript.Expr it, global::hscript.Expr e) {
			return new global::hscript.Expr_EFor(v, it, e);
		}
		
		
		public static readonly global::hscript.Expr EBreak = new global::hscript.Expr_EBreak();
		
		public static readonly global::hscript.Expr EContinue = new global::hscript.Expr_EContinue();
		
		public static global::hscript.Expr EFunction(global::Array<object> args, global::hscript.Expr e, string name, global::hscript.CType ret) {
			return new global::hscript.Expr_EFunction(args, e, name, ret);
		}
		
		
		public static global::hscript.Expr EReturn(global::hscript.Expr e) {
			return new global::hscript.Expr_EReturn(e);
		}
		
		
		public static global::hscript.Expr EArray(global::hscript.Expr e, global::hscript.Expr index) {
			return new global::hscript.Expr_EArray(e, index);
		}
		
		
		public static global::hscript.Expr EArrayDecl(global::Array<object> e) {
			return new global::hscript.Expr_EArrayDecl(e);
		}
		
		
		public static global::hscript.Expr ENew(string cl, global::Array<object> @params) {
			return new global::hscript.Expr_ENew(cl, @params);
		}
		
		
		public static global::hscript.Expr EThrow(global::hscript.Expr e) {
			return new global::hscript.Expr_EThrow(e);
		}
		
		
		public static global::hscript.Expr ETry(global::hscript.Expr e, string v, global::hscript.CType t, global::hscript.Expr ecatch) {
			return new global::hscript.Expr_ETry(e, v, t, ecatch);
		}
		
		
		public static global::hscript.Expr EObject(global::Array<object> fl) {
			return new global::hscript.Expr_EObject(fl);
		}
		
		
		public static global::hscript.Expr ETernary(global::hscript.Expr cond, global::hscript.Expr e1, global::hscript.Expr e2) {
			return new global::hscript.Expr_ETernary(cond, e1, e2);
		}
		
		
		public static global::hscript.Expr ESwitch(global::hscript.Expr e, global::Array<object> cases, global::hscript.Expr defaultExpr) {
			return new global::hscript.Expr_ESwitch(e, cases, defaultExpr);
		}
		
		
		public static global::hscript.Expr EDoWhile(global::hscript.Expr cond, global::hscript.Expr e) {
			return new global::hscript.Expr_EDoWhile(cond, e);
		}
		
		
		public static global::hscript.Expr EMeta(string name, global::Array<object> args, global::hscript.Expr e) {
			return new global::hscript.Expr_EMeta(name, args, e);
		}
		
		
		public static global::hscript.Expr ECheckType(global::hscript.Expr e, global::hscript.CType t) {
			return new global::hscript.Expr_ECheckType(e, t);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EConst : global::hscript.Expr {
		
		public Expr_EConst(global::hscript.Const c) : base(0) {
			this.c = c;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "EConst";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.c});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EConst en = ( other as global::hscript.Expr_EConst );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EConst", new object[]{this.c});
		}
		
		
		public readonly global::hscript.Const c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EIdent : global::hscript.Expr {
		
		public Expr_EIdent(string v) : base(1) {
			this.v = v;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EIdent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EIdent en = ( other as global::hscript.Expr_EIdent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EIdent", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EVar : global::hscript.Expr {
		
		public Expr_EVar(string n, global::hscript.CType t, global::hscript.Expr e) : base(2) {
			this.n = n;
			this.t = t;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.n, this.t, this.e});
		}
		
		
		public override string getTag() {
			return "EVar";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(2, new object[]{this.n, this.t, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EVar en = ( other as global::hscript.Expr_EVar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.n) ), ((object) (en.n) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EVar", new object[]{this.n, this.t, this.e});
		}
		
		
		public readonly string n;
		
		public readonly global::hscript.CType t;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EParent : global::hscript.Expr {
		
		public Expr_EParent(global::hscript.Expr e) : base(3) {
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EParent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(3, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EParent en = ( other as global::hscript.Expr_EParent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EParent", new object[]{this.e});
		}
		
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EBlock : global::hscript.Expr {
		
		public Expr_EBlock(global::Array<object> e) : base(4) {
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EBlock";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(4, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EBlock en = ( other as global::hscript.Expr_EBlock );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EBlock", new object[]{this.e});
		}
		
		
		public readonly global::Array<object> e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EField : global::hscript.Expr {
		
		public Expr_EField(global::hscript.Expr e, string f) : base(5) {
			this.e = e;
			this.f = f;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.f});
		}
		
		
		public override string getTag() {
			return "EField";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(5, new object[]{this.e, this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EField en = ( other as global::hscript.Expr_EField );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EField", new object[]{this.e, this.f});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly string f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EBinop : global::hscript.Expr {
		
		public Expr_EBinop(string op, global::hscript.Expr e1, global::hscript.Expr e2) : base(6) {
			this.op = op;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.op, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "EBinop";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(6, new object[]{this.op, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EBinop en = ( other as global::hscript.Expr_EBinop );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EBinop", new object[]{this.op, this.e1, this.e2});
		}
		
		
		public readonly string op;
		
		public readonly global::hscript.Expr e1;
		
		public readonly global::hscript.Expr e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EUnop : global::hscript.Expr {
		
		public Expr_EUnop(string op, bool prefix, global::hscript.Expr e) : base(7) {
			this.op = op;
			this.prefix = prefix;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.op, this.prefix, this.e});
		}
		
		
		public override string getTag() {
			return "EUnop";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(7, new object[]{this.op, this.prefix, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EUnop en = ( other as global::hscript.Expr_EUnop );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.prefix) ), ((object) (en.prefix) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EUnop", new object[]{this.op, this.prefix, this.e});
		}
		
		
		public readonly string op;
		
		public readonly bool prefix;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ECall : global::hscript.Expr {
		
		public Expr_ECall(global::hscript.Expr e, global::Array<object> @params) : base(8) {
			this.e = e;
			this.@params = @params;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.@params});
		}
		
		
		public override string getTag() {
			return "ECall";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(8, new object[]{this.e, this.@params});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ECall en = ( other as global::hscript.Expr_ECall );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ECall", new object[]{this.e, this.@params});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly global::Array<object> @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EIf : global::hscript.Expr {
		
		public Expr_EIf(global::hscript.Expr cond, global::hscript.Expr e1, global::hscript.Expr e2) : base(9) {
			this.cond = cond;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "EIf";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(9, new object[]{this.cond, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EIf en = ( other as global::hscript.Expr_EIf );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EIf", new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public readonly global::hscript.Expr cond;
		
		public readonly global::hscript.Expr e1;
		
		public readonly global::hscript.Expr e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EWhile : global::hscript.Expr {
		
		public Expr_EWhile(global::hscript.Expr cond, global::hscript.Expr e) : base(10) {
			this.cond = cond;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.cond, this.e});
		}
		
		
		public override string getTag() {
			return "EWhile";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(10, new object[]{this.cond, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EWhile en = ( other as global::hscript.Expr_EWhile );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EWhile", new object[]{this.cond, this.e});
		}
		
		
		public readonly global::hscript.Expr cond;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EFor : global::hscript.Expr {
		
		public Expr_EFor(string v, global::hscript.Expr it, global::hscript.Expr e) : base(11) {
			this.v = v;
			this.it = it;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v, this.it, this.e});
		}
		
		
		public override string getTag() {
			return "EFor";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(11, new object[]{this.v, this.it, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EFor en = ( other as global::hscript.Expr_EFor );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.it) ), ((object) (en.it) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EFor", new object[]{this.v, this.it, this.e});
		}
		
		
		public readonly string v;
		
		public readonly global::hscript.Expr it;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EBreak : global::hscript.Expr {
		
		public Expr_EBreak() : base(12) {
		}
		
		
		public override string getTag() {
			return "EBreak";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EContinue : global::hscript.Expr {
		
		public Expr_EContinue() : base(13) {
		}
		
		
		public override string getTag() {
			return "EContinue";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EFunction : global::hscript.Expr {
		
		public Expr_EFunction(global::Array<object> args, global::hscript.Expr e, string name, global::hscript.CType ret) : base(14) {
			this.args = args;
			this.e = e;
			this.name = name;
			this.ret = ret;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.args, this.e, this.name, this.ret});
		}
		
		
		public override string getTag() {
			return "EFunction";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(14, new object[]{this.args, this.e, this.name, this.ret});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EFunction en = ( other as global::hscript.Expr_EFunction );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.name) ), ((object) (en.name) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.ret) ), ((object) (en.ret) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EFunction", new object[]{this.args, this.e, this.name, this.ret});
		}
		
		
		public readonly global::Array<object> args;
		
		public readonly global::hscript.Expr e;
		
		public readonly string name;
		
		public readonly global::hscript.CType ret;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EReturn : global::hscript.Expr {
		
		public Expr_EReturn(global::hscript.Expr e) : base(15) {
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EReturn";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(15, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EReturn en = ( other as global::hscript.Expr_EReturn );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EReturn", new object[]{this.e});
		}
		
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EArray : global::hscript.Expr {
		
		public Expr_EArray(global::hscript.Expr e, global::hscript.Expr index) : base(16) {
			this.e = e;
			this.index = index;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.index});
		}
		
		
		public override string getTag() {
			return "EArray";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(16, new object[]{this.e, this.index});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EArray en = ( other as global::hscript.Expr_EArray );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.index) ), ((object) (en.index) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EArray", new object[]{this.e, this.index});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly global::hscript.Expr index;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EArrayDecl : global::hscript.Expr {
		
		public Expr_EArrayDecl(global::Array<object> e) : base(17) {
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EArrayDecl";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(17, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EArrayDecl en = ( other as global::hscript.Expr_EArrayDecl );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EArrayDecl", new object[]{this.e});
		}
		
		
		public readonly global::Array<object> e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ENew : global::hscript.Expr {
		
		public Expr_ENew(string cl, global::Array<object> @params) : base(18) {
			this.cl = cl;
			this.@params = @params;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.cl, this.@params});
		}
		
		
		public override string getTag() {
			return "ENew";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(18, new object[]{this.cl, this.@params});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ENew en = ( other as global::hscript.Expr_ENew );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cl) ), ((object) (en.cl) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ENew", new object[]{this.cl, this.@params});
		}
		
		
		public readonly string cl;
		
		public readonly global::Array<object> @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EThrow : global::hscript.Expr {
		
		public Expr_EThrow(global::hscript.Expr e) : base(19) {
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e});
		}
		
		
		public override string getTag() {
			return "EThrow";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(19, new object[]{this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EThrow en = ( other as global::hscript.Expr_EThrow );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EThrow", new object[]{this.e});
		}
		
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ETry : global::hscript.Expr {
		
		public Expr_ETry(global::hscript.Expr e, string v, global::hscript.CType t, global::hscript.Expr ecatch) : base(20) {
			this.e = e;
			this.v = v;
			this.t = t;
			this.ecatch = ecatch;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.v, this.t, this.ecatch});
		}
		
		
		public override string getTag() {
			return "ETry";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(20, new object[]{this.e, this.v, this.t, this.ecatch});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ETry en = ( other as global::hscript.Expr_ETry );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.ecatch) ), ((object) (en.ecatch) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ETry", new object[]{this.e, this.v, this.t, this.ecatch});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly string v;
		
		public readonly global::hscript.CType t;
		
		public readonly global::hscript.Expr ecatch;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EObject : global::hscript.Expr {
		
		public Expr_EObject(global::Array<object> fl) : base(21) {
			this.fl = fl;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.fl});
		}
		
		
		public override string getTag() {
			return "EObject";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(21, new object[]{this.fl});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EObject en = ( other as global::hscript.Expr_EObject );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.fl) ), ((object) (en.fl) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EObject", new object[]{this.fl});
		}
		
		
		public readonly global::Array<object> fl;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ETernary : global::hscript.Expr {
		
		public Expr_ETernary(global::hscript.Expr cond, global::hscript.Expr e1, global::hscript.Expr e2) : base(22) {
			this.cond = cond;
			this.e1 = e1;
			this.e2 = e2;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public override string getTag() {
			return "ETernary";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(22, new object[]{this.cond, this.e1, this.e2});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ETernary en = ( other as global::hscript.Expr_ETernary );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e1) ), ((object) (en.e1) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e2) ), ((object) (en.e2) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ETernary", new object[]{this.cond, this.e1, this.e2});
		}
		
		
		public readonly global::hscript.Expr cond;
		
		public readonly global::hscript.Expr e1;
		
		public readonly global::hscript.Expr e2;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ESwitch : global::hscript.Expr {
		
		public Expr_ESwitch(global::hscript.Expr e, global::Array<object> cases, global::hscript.Expr defaultExpr) : base(23) {
			this.e = e;
			this.cases = cases;
			this.defaultExpr = defaultExpr;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.cases, this.defaultExpr});
		}
		
		
		public override string getTag() {
			return "ESwitch";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(23, new object[]{this.e, this.cases, this.defaultExpr});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ESwitch en = ( other as global::hscript.Expr_ESwitch );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cases) ), ((object) (en.cases) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.defaultExpr) ), ((object) (en.defaultExpr) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ESwitch", new object[]{this.e, this.cases, this.defaultExpr});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly global::Array<object> cases;
		
		public readonly global::hscript.Expr defaultExpr;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EDoWhile : global::hscript.Expr {
		
		public Expr_EDoWhile(global::hscript.Expr cond, global::hscript.Expr e) : base(24) {
			this.cond = cond;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.cond, this.e});
		}
		
		
		public override string getTag() {
			return "EDoWhile";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(24, new object[]{this.cond, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EDoWhile en = ( other as global::hscript.Expr_EDoWhile );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.cond) ), ((object) (en.cond) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EDoWhile", new object[]{this.cond, this.e});
		}
		
		
		public readonly global::hscript.Expr cond;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_EMeta : global::hscript.Expr {
		
		public Expr_EMeta(string name, global::Array<object> args, global::hscript.Expr e) : base(25) {
			this.name = name;
			this.args = args;
			this.e = e;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.name, this.args, this.e});
		}
		
		
		public override string getTag() {
			return "EMeta";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(25, new object[]{this.name, this.args, this.e});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_EMeta en = ( other as global::hscript.Expr_EMeta );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.name) ), ((object) (en.name) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EMeta", new object[]{this.name, this.args, this.e});
		}
		
		
		public readonly string name;
		
		public readonly global::Array<object> args;
		
		public readonly global::hscript.Expr e;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Expr_ECheckType : global::hscript.Expr {
		
		public Expr_ECheckType(global::hscript.Expr e, global::hscript.CType t) : base(26) {
			this.e = e;
			this.t = t;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.e, this.t});
		}
		
		
		public override string getTag() {
			return "ECheckType";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(26, new object[]{this.e, this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Expr_ECheckType en = ( other as global::hscript.Expr_ECheckType );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.e) ), ((object) (en.e) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ECheckType", new object[]{this.e, this.t});
		}
		
		
		public readonly global::hscript.Expr e;
		
		public readonly global::hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class CType : global::haxe.lang.Enum {
		
		protected CType(int index) : base(index) {
		}
		
		
		public static global::hscript.CType CTPath(global::Array<string> path, global::Array<object> @params) {
			return new global::hscript.CType_CTPath(path, @params);
		}
		
		
		public static global::hscript.CType CTFun(global::Array<object> args, global::hscript.CType ret) {
			return new global::hscript.CType_CTFun(args, ret);
		}
		
		
		public static global::hscript.CType CTAnon(global::Array<object> fields) {
			return new global::hscript.CType_CTAnon(fields);
		}
		
		
		public static global::hscript.CType CTParent(global::hscript.CType t) {
			return new global::hscript.CType_CTParent(t);
		}
		
		
		public static global::hscript.CType CTOpt(global::hscript.CType t) {
			return new global::hscript.CType_CTOpt(t);
		}
		
		
		public static global::hscript.CType CTNamed(string n, global::hscript.CType t) {
			return new global::hscript.CType_CTNamed(n, t);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTPath : global::hscript.CType {
		
		public CType_CTPath(global::Array<string> path, global::Array<object> @params) : base(0) {
			this.path = path;
			this.@params = @params;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.path, this.@params});
		}
		
		
		public override string getTag() {
			return "CTPath";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.path, this.@params});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTPath en = ( other as global::hscript.CType_CTPath );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.@params) ), ((object) (en.@params) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTPath", new object[]{this.path, this.@params});
		}
		
		
		public readonly global::Array<string> path;
		
		public readonly global::Array<object> @params;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTFun : global::hscript.CType {
		
		public CType_CTFun(global::Array<object> args, global::hscript.CType ret) : base(1) {
			this.args = args;
			this.ret = ret;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.args, this.ret});
		}
		
		
		public override string getTag() {
			return "CTFun";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.args, this.ret});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTFun en = ( other as global::hscript.CType_CTFun );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.args) ), ((object) (en.args) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.ret) ), ((object) (en.ret) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTFun", new object[]{this.args, this.ret});
		}
		
		
		public readonly global::Array<object> args;
		
		public readonly global::hscript.CType ret;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTAnon : global::hscript.CType {
		
		public CType_CTAnon(global::Array<object> fields) : base(2) {
			this.fields = fields;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.fields});
		}
		
		
		public override string getTag() {
			return "CTAnon";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(2, new object[]{this.fields});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTAnon en = ( other as global::hscript.CType_CTAnon );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.fields) ), ((object) (en.fields) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTAnon", new object[]{this.fields});
		}
		
		
		public readonly global::Array<object> fields;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTParent : global::hscript.CType {
		
		public CType_CTParent(global::hscript.CType t) : base(3) {
			this.t = t;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.t});
		}
		
		
		public override string getTag() {
			return "CTParent";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(3, new object[]{this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTParent en = ( other as global::hscript.CType_CTParent );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTParent", new object[]{this.t});
		}
		
		
		public readonly global::hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTOpt : global::hscript.CType {
		
		public CType_CTOpt(global::hscript.CType t) : base(4) {
			this.t = t;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.t});
		}
		
		
		public override string getTag() {
			return "CTOpt";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(4, new object[]{this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTOpt en = ( other as global::hscript.CType_CTOpt );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTOpt", new object[]{this.t});
		}
		
		
		public readonly global::hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class CType_CTNamed : global::hscript.CType {
		
		public CType_CTNamed(string n, global::hscript.CType t) : base(5) {
			this.n = n;
			this.t = t;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.n, this.t});
		}
		
		
		public override string getTag() {
			return "CTNamed";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(5, new object[]{this.n, this.t});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.CType_CTNamed en = ( other as global::hscript.CType_CTNamed );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.n) ), ((object) (en.n) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.t) ), ((object) (en.t) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("CTNamed", new object[]{this.n, this.t});
		}
		
		
		public readonly string n;
		
		public readonly global::hscript.CType t;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Error : global::haxe.lang.Enum {
		
		protected Error(int index) : base(index) {
		}
		
		
		public static global::hscript.Error EInvalidChar(int c) {
			return new global::hscript.Error_EInvalidChar(c);
		}
		
		
		public static global::hscript.Error EUnexpected(string s) {
			return new global::hscript.Error_EUnexpected(s);
		}
		
		
		public static readonly global::hscript.Error EUnterminatedString = new global::hscript.Error_EUnterminatedString();
		
		public static readonly global::hscript.Error EUnterminatedComment = new global::hscript.Error_EUnterminatedComment();
		
		public static global::hscript.Error EInvalidPreprocessor(string msg) {
			return new global::hscript.Error_EInvalidPreprocessor(msg);
		}
		
		
		public static global::hscript.Error EUnknownVariable(string v) {
			return new global::hscript.Error_EUnknownVariable(v);
		}
		
		
		public static global::hscript.Error EInvalidIterator(string v) {
			return new global::hscript.Error_EInvalidIterator(v);
		}
		
		
		public static global::hscript.Error EInvalidOp(string op) {
			return new global::hscript.Error_EInvalidOp(op);
		}
		
		
		public static global::hscript.Error EInvalidAccess(string f) {
			return new global::hscript.Error_EInvalidAccess(f);
		}
		
		
		public static global::hscript.Error ECustom(string msg) {
			return new global::hscript.Error_ECustom(msg);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EInvalidChar : global::hscript.Error {
		
		public Error_EInvalidChar(int c) : base(0) {
			this.c = c;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "EInvalidChar";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.c});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EInvalidChar en = ( other as global::hscript.Error_EInvalidChar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EInvalidChar", new object[]{this.c});
		}
		
		
		public readonly int c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EUnexpected : global::hscript.Error {
		
		public Error_EUnexpected(string s) : base(1) {
			this.s = s;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.s});
		}
		
		
		public override string getTag() {
			return "EUnexpected";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.s});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EUnexpected en = ( other as global::hscript.Error_EUnexpected );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.s) ), ((object) (en.s) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EUnexpected", new object[]{this.s});
		}
		
		
		public readonly string s;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EUnterminatedString : global::hscript.Error {
		
		public Error_EUnterminatedString() : base(2) {
		}
		
		
		public override string getTag() {
			return "EUnterminatedString";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EUnterminatedComment : global::hscript.Error {
		
		public Error_EUnterminatedComment() : base(3) {
		}
		
		
		public override string getTag() {
			return "EUnterminatedComment";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EInvalidPreprocessor : global::hscript.Error {
		
		public Error_EInvalidPreprocessor(string msg) : base(4) {
			this.msg = msg;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.msg});
		}
		
		
		public override string getTag() {
			return "EInvalidPreprocessor";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(4, new object[]{this.msg});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EInvalidPreprocessor en = ( other as global::hscript.Error_EInvalidPreprocessor );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.msg) ), ((object) (en.msg) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EInvalidPreprocessor", new object[]{this.msg});
		}
		
		
		public readonly string msg;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EUnknownVariable : global::hscript.Error {
		
		public Error_EUnknownVariable(string v) : base(5) {
			this.v = v;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EUnknownVariable";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(5, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EUnknownVariable en = ( other as global::hscript.Error_EUnknownVariable );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EUnknownVariable", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EInvalidIterator : global::hscript.Error {
		
		public Error_EInvalidIterator(string v) : base(6) {
			this.v = v;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "EInvalidIterator";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(6, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EInvalidIterator en = ( other as global::hscript.Error_EInvalidIterator );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EInvalidIterator", new object[]{this.v});
		}
		
		
		public readonly string v;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EInvalidOp : global::hscript.Error {
		
		public Error_EInvalidOp(string op) : base(7) {
			this.op = op;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.op});
		}
		
		
		public override string getTag() {
			return "EInvalidOp";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(7, new object[]{this.op});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EInvalidOp en = ( other as global::hscript.Error_EInvalidOp );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.op) ), ((object) (en.op) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EInvalidOp", new object[]{this.op});
		}
		
		
		public readonly string op;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_EInvalidAccess : global::hscript.Error {
		
		public Error_EInvalidAccess(string f) : base(8) {
			this.f = f;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "EInvalidAccess";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(8, new object[]{this.f});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_EInvalidAccess en = ( other as global::hscript.Error_EInvalidAccess );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("EInvalidAccess", new object[]{this.f});
		}
		
		
		public readonly string f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class Error_ECustom : global::hscript.Error {
		
		public Error_ECustom(string msg) : base(9) {
			this.msg = msg;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.msg});
		}
		
		
		public override string getTag() {
			return "ECustom";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(9, new object[]{this.msg});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.Error_ECustom en = ( other as global::hscript.Error_ECustom );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.msg) ), ((object) (en.msg) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("ECustom", new object[]{this.msg});
		}
		
		
		public readonly string msg;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class ModuleDecl : global::haxe.lang.Enum {
		
		protected ModuleDecl(int index) : base(index) {
		}
		
		
		public static global::hscript.ModuleDecl DPackage(global::Array<string> path) {
			return new global::hscript.ModuleDecl_DPackage(path);
		}
		
		
		public static global::hscript.ModuleDecl DImport(global::Array<string> path, global::haxe.lang.Null<bool> everything) {
			return new global::hscript.ModuleDecl_DImport(path, everything);
		}
		
		
		public static global::hscript.ModuleDecl DClass(object c) {
			return new global::hscript.ModuleDecl_DClass(c);
		}
		
		
		public static global::hscript.ModuleDecl DTypedef(object c) {
			return new global::hscript.ModuleDecl_DTypedef(c);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class ModuleDecl_DPackage : global::hscript.ModuleDecl {
		
		public ModuleDecl_DPackage(global::Array<string> path) : base(0) {
			this.path = path;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.path});
		}
		
		
		public override string getTag() {
			return "DPackage";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.path});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.ModuleDecl_DPackage en = ( other as global::hscript.ModuleDecl_DPackage );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("DPackage", new object[]{this.path});
		}
		
		
		public readonly global::Array<string> path;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class ModuleDecl_DImport : global::hscript.ModuleDecl {
		
		public ModuleDecl_DImport(global::Array<string> path, global::haxe.lang.Null<bool> everything) : base(1) {
			this.path = path;
			this.everything = everything;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.path, (this.everything).toDynamic()});
		}
		
		
		public override string getTag() {
			return "DImport";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.path, (this.everything).toDynamic()});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.ModuleDecl_DImport en = ( other as global::hscript.ModuleDecl_DImport );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.path) ), ((object) (en.path) ))) ) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>((this.everything).toDynamic(), (en.everything).toDynamic())) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("DImport", new object[]{this.path, (this.everything).toDynamic()});
		}
		
		
		public readonly global::Array<string> path;
		
		public readonly global::haxe.lang.Null<bool> everything;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class ModuleDecl_DClass : global::hscript.ModuleDecl {
		
		public ModuleDecl_DClass(object c) : base(2) {
			this.c = c;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "DClass";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(2, new object[]{this.c});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.ModuleDecl_DClass en = ( other as global::hscript.ModuleDecl_DClass );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("DClass", new object[]{this.c});
		}
		
		
		public readonly object c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class ModuleDecl_DTypedef : global::hscript.ModuleDecl {
		
		public ModuleDecl_DTypedef(object c) : base(3) {
			this.c = c;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.c});
		}
		
		
		public override string getTag() {
			return "DTypedef";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(3, new object[]{this.c});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.ModuleDecl_DTypedef en = ( other as global::hscript.ModuleDecl_DTypedef );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.c) ), ((object) (en.c) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("DTypedef", new object[]{this.c});
		}
		
		
		public readonly object c;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class FieldAccess : global::haxe.lang.Enum {
		
		protected FieldAccess(int index) : base(index) {
		}
		
		
		public static readonly global::hscript.FieldAccess APublic = new global::hscript.FieldAccess_APublic();
		
		public static readonly global::hscript.FieldAccess APrivate = new global::hscript.FieldAccess_APrivate();
		
		public static readonly global::hscript.FieldAccess AInline = new global::hscript.FieldAccess_AInline();
		
		public static readonly global::hscript.FieldAccess AOverride = new global::hscript.FieldAccess_AOverride();
		
		public static readonly global::hscript.FieldAccess AStatic = new global::hscript.FieldAccess_AStatic();
		
		public static readonly global::hscript.FieldAccess AMacro = new global::hscript.FieldAccess_AMacro();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_APublic : global::hscript.FieldAccess {
		
		public FieldAccess_APublic() : base(0) {
		}
		
		
		public override string getTag() {
			return "APublic";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_APrivate : global::hscript.FieldAccess {
		
		public FieldAccess_APrivate() : base(1) {
		}
		
		
		public override string getTag() {
			return "APrivate";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_AInline : global::hscript.FieldAccess {
		
		public FieldAccess_AInline() : base(2) {
		}
		
		
		public override string getTag() {
			return "AInline";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_AOverride : global::hscript.FieldAccess {
		
		public FieldAccess_AOverride() : base(3) {
		}
		
		
		public override string getTag() {
			return "AOverride";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_AStatic : global::hscript.FieldAccess {
		
		public FieldAccess_AStatic() : base(4) {
		}
		
		
		public override string getTag() {
			return "AStatic";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldAccess_AMacro : global::hscript.FieldAccess {
		
		public FieldAccess_AMacro() : base(5) {
		}
		
		
		public override string getTag() {
			return "AMacro";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class FieldKind : global::haxe.lang.Enum {
		
		protected FieldKind(int index) : base(index) {
		}
		
		
		public static global::hscript.FieldKind KFunction(object f) {
			return new global::hscript.FieldKind_KFunction(f);
		}
		
		
		public static global::hscript.FieldKind KVar(object v) {
			return new global::hscript.FieldKind_KVar(v);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldKind_KFunction : global::hscript.FieldKind {
		
		public FieldKind_KFunction(object f) : base(0) {
			this.f = f;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.f});
		}
		
		
		public override string getTag() {
			return "KFunction";
		}
		
		
		public override int GetHashCode() {
			return global::haxe.lang.Enum.paramsGetHashCode(0, new object[]{this.f});
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.FieldKind_KFunction en = ( other as global::hscript.FieldKind_KFunction );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.f) ), ((object) (en.f) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("KFunction", new object[]{this.f});
		}
		
		
		public readonly object f;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public sealed class FieldKind_KVar : global::hscript.FieldKind {
		
		public FieldKind_KVar(object v) : base(1) {
			this.v = v;
		}
		
		
		public override global::Array<object> getParams() {
			return new global::Array<object>(new object[]{this.v});
		}
		
		
		public override string getTag() {
			return "KVar";
		}
		
		
		public override int GetHashCode() {
			unchecked {
				return global::haxe.lang.Enum.paramsGetHashCode(1, new object[]{this.v});
			}
		}
		
		
		public override bool Equals(object other) {
			if (global::System.Object.ReferenceEquals(((object) (this) ), ((object) (other) ))) {
				return true;
			}
			
			global::hscript.FieldKind_KVar en = ( other as global::hscript.FieldKind_KVar );
			if (( en == null )) {
				return false;
			}
			
			if ( ! (global::Type.enumEq<object>(((object) (this.v) ), ((object) (en.v) ))) ) {
				return false;
			}
			
			return true;
		}
		
		
		public override string toString() {
			return global::haxe.lang.Enum.paramsToString("KVar", new object[]{this.v});
		}
		
		
		public readonly object v;
		
	}
}


