// Generated by Haxe 4.1.5

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript._Interp {
	public class Stop : global::haxe.lang.Enum {
		
		protected Stop(int index) : base(index) {
		}
		
		
		public static readonly global::hscript._Interp.Stop SBreak = new global::hscript._Interp.Stop_SBreak();
		
		public static readonly global::hscript._Interp.Stop SContinue = new global::hscript._Interp.Stop_SContinue();
		
		public static readonly global::hscript._Interp.Stop SReturn = new global::hscript._Interp.Stop_SReturn();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript._Interp {
	public sealed class Stop_SBreak : global::hscript._Interp.Stop {
		
		public Stop_SBreak() : base(0) {
		}
		
		
		public override string getTag() {
			return "SBreak";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript._Interp {
	public sealed class Stop_SContinue : global::hscript._Interp.Stop {
		
		public Stop_SContinue() : base(1) {
		}
		
		
		public override string getTag() {
			return "SContinue";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript._Interp {
	public sealed class Stop_SReturn : global::hscript._Interp.Stop {
		
		public Stop_SReturn() : base(2) {
		}
		
		
		public override string getTag() {
			return "SReturn";
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp : global::haxe.lang.HxObject {
		
		public Interp(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Interp() {
			global::hscript.Interp.__hx_ctor_hscript_Interp(this);
		}
		
		
		protected static void __hx_ctor_hscript_Interp(global::hscript.Interp __hx_this) {
			__hx_this.locals = new global::haxe.ds.StringMap<object>();
			__hx_this.declared = new global::Array<object>();
			__hx_this.resetVariables();
			__hx_this.initOps();
		}
		
		
		public global::haxe.ds.StringMap variables;
		
		public global::haxe.ds.StringMap<object> locals;
		
		public global::haxe.ds.StringMap<object> binops;
		
		public int depth;
		
		public bool inTry;
		
		public global::Array<object> declared;
		
		public object returnValue;
		
		public virtual void resetVariables() {
			global::hscript.Interp _gthis = this;
			this.variables = new global::haxe.ds.StringMap<object>();
			{
				object @value = null;
				object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{"null", @value})) );
			}
			
			object __temp_expr2 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{"true", true})) );
			object __temp_expr3 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{"false", false})) );
			object __temp_expr4 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{"trace", global::Reflect.makeVarArgs(((global::haxe.lang.Function) (new global::hscript.Interp_resetVariables_74__Fun(_gthis)) ))})) );
		}
		
		
		public virtual object posInfos() {
			return ((object) (new global::haxe.lang.DynamicObject(new int[]{1648581351}, new object[]{"hscript"}, new int[]{1981972957}, new double[]{((double) (0) )})) );
		}
		
		
		public virtual void initOps() {
			global::hscript.Interp me = this;
			this.binops = new global::haxe.ds.StringMap<object>();
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("+", new global::hscript.Interp_initOps_97__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("-", new global::hscript.Interp_initOps_98__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("*", new global::hscript.Interp_initOps_99__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("/", new global::hscript.Interp_initOps_100__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("%", new global::hscript.Interp_initOps_101__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("&", new global::hscript.Interp_initOps_102__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("|", new global::hscript.Interp_initOps_103__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("^", new global::hscript.Interp_initOps_104__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("<<", new global::hscript.Interp_initOps_105__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set(">>", new global::hscript.Interp_initOps_106__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set(">>>", new global::hscript.Interp_initOps_107__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("==", new global::hscript.Interp_initOps_108__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("!=", new global::hscript.Interp_initOps_109__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set(">=", new global::hscript.Interp_initOps_110__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("<=", new global::hscript.Interp_initOps_111__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set(">", new global::hscript.Interp_initOps_112__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("<", new global::hscript.Interp_initOps_113__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("||", new global::hscript.Interp_initOps_114__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("&&", new global::hscript.Interp_initOps_115__Fun(me));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("=", ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "assign", 1275479599)) ));
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set("...", new global::hscript.Interp_initOps_117__Fun(me));
			this.assignOp("+=", ( (( global::hscript.Interp_initOps_118__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_118__Fun.__hx_current) : (global::hscript.Interp_initOps_118__Fun.__hx_current = ((global::hscript.Interp_initOps_118__Fun) (new global::hscript.Interp_initOps_118__Fun()) )) ));
			this.assignOp("-=", ( (( global::hscript.Interp_initOps_119__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_119__Fun.__hx_current) : (global::hscript.Interp_initOps_119__Fun.__hx_current = ((global::hscript.Interp_initOps_119__Fun) (new global::hscript.Interp_initOps_119__Fun()) )) ));
			this.assignOp("*=", ( (( global::hscript.Interp_initOps_120__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_120__Fun.__hx_current) : (global::hscript.Interp_initOps_120__Fun.__hx_current = ((global::hscript.Interp_initOps_120__Fun) (new global::hscript.Interp_initOps_120__Fun()) )) ));
			this.assignOp("/=", ( (( global::hscript.Interp_initOps_121__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_121__Fun.__hx_current) : (global::hscript.Interp_initOps_121__Fun.__hx_current = ((global::hscript.Interp_initOps_121__Fun) (new global::hscript.Interp_initOps_121__Fun()) )) ));
			this.assignOp("%=", ( (( global::hscript.Interp_initOps_122__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_122__Fun.__hx_current) : (global::hscript.Interp_initOps_122__Fun.__hx_current = ((global::hscript.Interp_initOps_122__Fun) (new global::hscript.Interp_initOps_122__Fun()) )) ));
			this.assignOp("&=", ( (( global::hscript.Interp_initOps_123__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_123__Fun.__hx_current) : (global::hscript.Interp_initOps_123__Fun.__hx_current = ((global::hscript.Interp_initOps_123__Fun) (new global::hscript.Interp_initOps_123__Fun()) )) ));
			this.assignOp("|=", ( (( global::hscript.Interp_initOps_124__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_124__Fun.__hx_current) : (global::hscript.Interp_initOps_124__Fun.__hx_current = ((global::hscript.Interp_initOps_124__Fun) (new global::hscript.Interp_initOps_124__Fun()) )) ));
			this.assignOp("^=", ( (( global::hscript.Interp_initOps_125__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_125__Fun.__hx_current) : (global::hscript.Interp_initOps_125__Fun.__hx_current = ((global::hscript.Interp_initOps_125__Fun) (new global::hscript.Interp_initOps_125__Fun()) )) ));
			this.assignOp("<<=", ( (( global::hscript.Interp_initOps_126__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_126__Fun.__hx_current) : (global::hscript.Interp_initOps_126__Fun.__hx_current = ((global::hscript.Interp_initOps_126__Fun) (new global::hscript.Interp_initOps_126__Fun()) )) ));
			this.assignOp(">>=", ( (( global::hscript.Interp_initOps_127__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_127__Fun.__hx_current) : (global::hscript.Interp_initOps_127__Fun.__hx_current = ((global::hscript.Interp_initOps_127__Fun) (new global::hscript.Interp_initOps_127__Fun()) )) ));
			this.assignOp(">>>=", ( (( global::hscript.Interp_initOps_128__Fun.__hx_current != null )) ? (global::hscript.Interp_initOps_128__Fun.__hx_current) : (global::hscript.Interp_initOps_128__Fun.__hx_current = ((global::hscript.Interp_initOps_128__Fun) (new global::hscript.Interp_initOps_128__Fun()) )) ));
		}
		
		
		public virtual object assign(global::hscript.Expr e1, global::hscript.Expr e2) {
			unchecked {
				object v = this.expr(e2);
				switch (e1._hx_index) {
					case 1:
					{
						string id = ( e1 as global::hscript.Expr_EIdent ).v;
						{
							object l = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(id)).@value;
							if (( l == null )) {
								object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{id, v})) );
							}
							else {
								global::haxe.lang.Runtime.setField(l, "r", 114, v);
							}
							
						}
						
						break;
					}
					
					
					case 5:
					{
						string f = ( e1 as global::hscript.Expr_EField ).f;
						global::hscript.Expr e = ( e1 as global::hscript.Expr_EField ).e;
						v = this.@set(this.expr(e), f, v);
						break;
					}
					
					
					case 16:
					{
						global::hscript.Expr index = ( e1 as global::hscript.Expr_EArray ).index;
						global::hscript.Expr e3 = ( e1 as global::hscript.Expr_EArray ).e;
						{
							object arr = this.expr(e3);
							object index1 = this.expr(index);
							if (global::Std.isOfType(arr, ((object) (typeof(global::haxe.IMap<object, object>)) ))) {
								object __temp_expr3 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "set", 5741474, new object[]{index1, ((object) (v) )})) );
							}
							else {
								object __temp_expr2 = ((object) (global::haxe.lang.Runtime.callField(arr, "__set", 1916009602, new object[]{index1, v})) );
							}
							
						}
						
						break;
					}
					
					
					default:
					{
						global::hscript.Error e4 = global::hscript.Error.EInvalidOp("=");
						throw ((global::System.Exception) (global::haxe.Exception.thrown(e4)) );
					}
					
				}
				
				return v;
			}
		}
		
		
		public virtual void assignOp(string op, global::haxe.lang.Function fop) {
			global::hscript.Interp me = this;
			((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@set(op, new global::hscript.Interp_assignOp_160__Fun(op, me, fop));
		}
		
		
		public virtual object evalAssignOp(string op, global::haxe.lang.Function fop, global::hscript.Expr e1, global::hscript.Expr e2) {
			unchecked {
				object v = null;
				switch (e1._hx_index) {
					case 1:
					{
						string id = ( e1 as global::hscript.Expr_EIdent ).v;
						{
							object l = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(id)).@value;
							v = ((object) (fop.__hx_invoke2_o(default(double), this.expr(e1), default(double), this.expr(e2))) );
							if (( l == null )) {
								object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{id, v})) );
							}
							else {
								global::haxe.lang.Runtime.setField(l, "r", 114, v);
							}
							
						}
						
						break;
					}
					
					
					case 5:
					{
						string f = ( e1 as global::hscript.Expr_EField ).f;
						global::hscript.Expr e = ( e1 as global::hscript.Expr_EField ).e;
						{
							object obj = this.expr(e);
							v = ((object) (fop.__hx_invoke2_o(default(double), this.@get(obj, f), default(double), this.expr(e2))) );
							v = this.@set(obj, f, v);
						}
						
						break;
					}
					
					
					case 16:
					{
						global::hscript.Expr index = ( e1 as global::hscript.Expr_EArray ).index;
						global::hscript.Expr e3 = ( e1 as global::hscript.Expr_EArray ).e;
						{
							object arr = this.expr(e3);
							object index1 = this.expr(index);
							if (global::Std.isOfType(arr, ((object) (typeof(global::haxe.IMap<object, object>)) ))) {
								v = ((object) (fop.__hx_invoke2_o(default(double), ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "get", 5144726, new object[]{index1})) ), default(double), this.expr(e2))) );
								object __temp_expr3 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "set", 5741474, new object[]{index1, ((object) (v) )})) );
							}
							else {
								v = ((object) (fop.__hx_invoke2_o(default(double), ((object) (global::haxe.lang.Runtime.callField(arr, "__get", 1915412854, new object[]{index1})) ), default(double), this.expr(e2))) );
								object __temp_expr2 = ((object) (global::haxe.lang.Runtime.callField(arr, "__set", 1916009602, new object[]{index1, v})) );
							}
							
						}
						
						break;
					}
					
					
					default:
					{
						global::hscript.Error e4 = global::hscript.Error.EInvalidOp(op);
						throw ((global::System.Exception) (global::haxe.Exception.thrown(e4)) );
					}
					
				}
				
				return v;
			}
		}
		
		
		public virtual object increment(global::hscript.Expr e, bool prefix, int delta) {
			unchecked {
				switch (e._hx_index) {
					case 1:
					{
						string id = ( e as global::hscript.Expr_EIdent ).v;
						object l = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(id)).@value;
						object v = ( (( l == null )) ? (((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "get", 5144726, new object[]{id})) )) : (global::haxe.lang.Runtime.getField(l, "r", 114, true)) );
						if (prefix) {
							v = ((object) (global::haxe.lang.Runtime.plus(v, delta)) );
							if (( l == null )) {
								object __temp_expr2 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{id, v})) );
							}
							else {
								global::haxe.lang.Runtime.setField(l, "r", 114, v);
							}
							
						}
						else if (( l == null )) {
							object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{id, ((object) (global::haxe.lang.Runtime.plus(v, delta)) )})) );
						}
						else {
							global::haxe.lang.Runtime.setField(l, "r", 114, ((object) (global::haxe.lang.Runtime.plus(v, delta)) ));
						}
						
						return v;
					}
					
					
					case 5:
					{
						string f = ( e as global::hscript.Expr_EField ).f;
						global::hscript.Expr e1 = ( e as global::hscript.Expr_EField ).e;
						object obj = this.expr(e1);
						object v1 = this.@get(obj, f);
						if (prefix) {
							v1 = ((object) (global::haxe.lang.Runtime.plus(v1, delta)) );
							this.@set(obj, f, v1);
						}
						else {
							this.@set(obj, f, ((object) (global::haxe.lang.Runtime.plus(v1, delta)) ));
						}
						
						return v1;
					}
					
					
					case 16:
					{
						global::hscript.Expr index = ( e as global::hscript.Expr_EArray ).index;
						global::hscript.Expr e2 = ( e as global::hscript.Expr_EArray ).e;
						object arr = this.expr(e2);
						object index1 = this.expr(index);
						if (global::Std.isOfType(arr, ((object) (typeof(global::haxe.IMap<object, object>)) ))) {
							int v2 = ((int) (global::haxe.lang.Runtime.toInt(((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "get", 5144726, new object[]{index1})) ))) );
							if (prefix) {
								v2 += delta;
								object __temp_expr6 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "set", 5741474, new object[]{index1, ((object) (v2) )})) );
							}
							else {
								object __temp_expr5 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "set", 5741474, new object[]{index1, ((object) (( v2 + delta )) )})) );
							}
							
							return v2;
						}
						else {
							int v3 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(arr, "__get", 1915412854, new object[]{index1}))) );
							if (prefix) {
								v3 += delta;
								int __temp_expr4 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(arr, "__set", 1916009602, new object[]{index1, v3}))) );
							}
							else {
								int __temp_expr3 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(arr, "__set", 1916009602, new object[]{index1, ( v3 + delta )}))) );
							}
							
							return v3;
						}
						
					}
					
					
					default:
					{
						global::hscript.Error e3 = global::hscript.Error.EInvalidOp(( (( delta > 0 )) ? ("++") : ("--") ));
						throw ((global::System.Exception) (global::haxe.Exception.thrown(e3)) );
					}
					
				}
				
			}
		}
		
		
		public virtual object execute(global::hscript.Expr expr) {
			this.depth = 0;
			this.locals = new global::haxe.ds.StringMap<object>();
			this.declared = new global::Array<object>();
			return this.exprReturn(expr);
		}
		
		
		public virtual object exprReturn(global::hscript.Expr e) {
			unchecked {
				try {
					return this.expr(e);
				}
				catch (global::System.Exception _g){
					object _g1 = global::haxe.Exception.caught(_g).unwrap();
					if (( _g1 is global::hscript._Interp.Stop )) {
						global::hscript._Interp.Stop e1 = ((global::hscript._Interp.Stop) (_g1) );
						switch (e1._hx_index) {
							case 0:
							{
								throw ((global::System.Exception) (global::haxe.Exception.thrown("Invalid break")) );
							}
							
							
							case 1:
							{
								throw ((global::System.Exception) (global::haxe.Exception.thrown("Invalid continue")) );
							}
							
							
							case 2:
							{
								object v = this.returnValue;
								this.returnValue = null;
								return v;
							}
							
							
						}
						
					}
					else {
						throw _g;
					}
					
				}
				
				
				return null;
			}
		}
		
		
		public virtual global::haxe.ds.StringMap<object> duplicate<T>(global::haxe.ds.StringMap<T> h) {
			global::haxe.ds.StringMap<object> h2 = new global::haxe.ds.StringMap<object>();
			{
				object k = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<T>(((global::haxe.ds.StringMap<T>) (h) ))) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(k, "hasNext", 407283053, null))) {
					string k1 = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(k, "next", 1224901875, null));
					h2.@set(k1, (h.@get(k1)).toDynamic());
				}
				
			}
			
			return h2;
		}
		
		
		public virtual void restore(int old) {
			while (( this.declared.length > old )) {
				object d = (this.declared.pop()).@value;
				((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@set(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(d, "n", 110, true)), global::haxe.lang.Runtime.getField(d, "old", 5544103, true));
			}
			
		}
		
		
		public object error(global::hscript.Error e, global::haxe.lang.Null<bool> rethrow) {
			bool rethrow1 = ( ( ! (rethrow.hasValue) ) ? (false) : ((rethrow).@value) );
			if (rethrow1) {
				throw ((global::System.Exception) (global::haxe.Exception.thrown(((object) (e) ))) );
			}
			else {
				throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
			}
			
		}
		
		
		public void rethrow(object e) {
			throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
		}
		
		
		public virtual object resolve(string id) {
			object l = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(id)).@value;
			if (( l != null )) {
				return global::haxe.lang.Runtime.getField(l, "r", 114, true);
			}
			
			object v = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "get", 5144726, new object[]{id})) );
			if (( ( v == null ) &&  ! (((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ).exists(id))  )) {
				global::hscript.Error e = global::hscript.Error.EUnknownVariable(id);
				throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
			}
			
			return v;
		}
		
		
		public virtual object expr(global::hscript.Expr e) {
			unchecked {
				global::hscript.Interp _gthis = this;
				switch (e._hx_index) {
					case 0:
					{
						global::hscript.Const c = ( e as global::hscript.Expr_EConst ).c;
						switch (c._hx_index) {
							case 0:
							{
								int v = ( c as global::hscript.Const_CInt ).v;
								return v;
							}
							
							
							case 1:
							{
								double f = ( c as global::hscript.Const_CFloat ).f;
								return f;
							}
							
							
							case 2:
							{
								string s = ( c as global::hscript.Const_CString ).s;
								return s;
							}
							
							
						}
						
						break;
					}
					
					
					case 1:
					{
						string id = ( e as global::hscript.Expr_EIdent ).v;
						return this.resolve(id);
					}
					
					
					case 2:
					{
						global::hscript.CType _g = ( e as global::hscript.Expr_EVar ).t;
						global::hscript.Expr e1 = ( e as global::hscript.Expr_EVar ).e;
						string n = ( e as global::hscript.Expr_EVar ).n;
						object __temp_stmt5 = null;
						{
							object __temp_odecl1 = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(n)).@value;
							__temp_stmt5 = new global::haxe.lang.DynamicObject(new int[]{110, 5544103}, new object[]{n, __temp_odecl1}, new int[]{}, new double[]{});
						}
						
						this.declared.push(__temp_stmt5);
						object __temp_stmt6 = null;
						{
							object __temp_odecl2 = ( (( e1 == null )) ? (null) : (this.expr(e1)) );
							__temp_stmt6 = new global::haxe.lang.DynamicObject(new int[]{114}, new object[]{__temp_odecl2}, new int[]{}, new double[]{});
						}
						
						((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@set(n, __temp_stmt6);
						return null;
					}
					
					
					case 3:
					{
						global::hscript.Expr e2 = ( e as global::hscript.Expr_EParent ).e;
						return this.expr(e2);
					}
					
					
					case 4:
					{
						global::Array<object> exprs = ( e as global::hscript.Expr_EBlock ).e;
						int old = this.declared.length;
						object v1 = null;
						{
							int _g1 = 0;
							while (( _g1 < exprs.length )) {
								global::hscript.Expr e3 = ((global::hscript.Expr) (exprs[_g1]) );
								 ++ _g1;
								v1 = this.expr(e3);
							}
							
						}
						
						this.restore(old);
						return v1;
					}
					
					
					case 5:
					{
						string f1 = ( e as global::hscript.Expr_EField ).f;
						global::hscript.Expr e4 = ( e as global::hscript.Expr_EField ).e;
						return this.@get(this.expr(e4), f1);
					}
					
					
					case 6:
					{
						global::hscript.Expr e21 = ( e as global::hscript.Expr_EBinop ).e2;
						global::hscript.Expr e11 = ( e as global::hscript.Expr_EBinop ).e1;
						string op = ( e as global::hscript.Expr_EBinop ).op;
						global::haxe.lang.Function fop = ((global::haxe.lang.Function) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.binops) )) ))) ).@get(op)).@value) );
						if (( fop == null )) {
							global::hscript.Error e5 = global::hscript.Error.EInvalidOp(op);
							throw ((global::System.Exception) (global::haxe.Exception.thrown(e5)) );
						}
						
						return ((object) (((global::haxe.lang.Function) (fop) ).__hx_invoke2_o(default(double), e11, default(double), e21)) );
					}
					
					
					case 7:
					{
						global::hscript.Expr e6 = ( e as global::hscript.Expr_EUnop ).e;
						bool prefix = ( e as global::hscript.Expr_EUnop ).prefix;
						string op1 = ( e as global::hscript.Expr_EUnop ).op;
						switch (op1) {
							case "!":
							{
								return ( ! (global::haxe.lang.Runtime.eq(this.expr(e6), true)) );
							}
							
							
							case "++":
							{
								return this.increment(e6, prefix, 1);
							}
							
							
							case "-":
							{
								return ( - (((double) (global::haxe.lang.Runtime.toDouble(this.expr(e6))) )) );
							}
							
							
							case "--":
							{
								return this.increment(e6, prefix, -1);
							}
							
							
							case "~":
							{
								return ( ~ (((int) (global::haxe.lang.Runtime.toInt(this.expr(e6))) )) );
							}
							
							
							default:
							{
								global::hscript.Error e7 = global::hscript.Error.EInvalidOp(op1);
								throw ((global::System.Exception) (global::haxe.Exception.thrown(e7)) );
							}
							
						}
						
					}
					
					
					case 8:
					{
						global::Array<object> @params = ( e as global::hscript.Expr_ECall ).@params;
						global::hscript.Expr e8 = ( e as global::hscript.Expr_ECall ).e;
						global::Array args = new global::Array<object>();
						{
							int _g2 = 0;
							while (( _g2 < @params.length )) {
								global::hscript.Expr p = ((global::hscript.Expr) (@params[_g2]) );
								 ++ _g2;
								int __temp_expr7 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(args, "push", 1247875546, new object[]{this.expr(p)}))) );
							}
							
						}
						
						if (( e8._hx_index == 5 )) {
							string f2 = ( e8 as global::hscript.Expr_EField ).f;
							global::hscript.Expr e9 = ( e8 as global::hscript.Expr_EField ).e;
							object obj = this.expr(e9);
							if (( obj == null )) {
								global::hscript.Error e10 = global::hscript.Error.EInvalidAccess(f2);
								throw ((global::System.Exception) (global::haxe.Exception.thrown(e10)) );
							}
							
							return this.fcall(obj, f2, args);
						}
						else {
							return this.call(null, this.expr(e8), args);
						}
						
					}
					
					
					case 9:
					{
						global::hscript.Expr e22 = ( e as global::hscript.Expr_EIf ).e2;
						global::hscript.Expr e12 = ( e as global::hscript.Expr_EIf ).e1;
						global::hscript.Expr econd = ( e as global::hscript.Expr_EIf ).cond;
						if (global::haxe.lang.Runtime.eq(this.expr(econd), true)) {
							return this.expr(e12);
						}
						else if (( e22 == null )) {
							return null;
						}
						else {
							return this.expr(e22);
						}
						
					}
					
					
					case 10:
					{
						global::hscript.Expr e13 = ( e as global::hscript.Expr_EWhile ).e;
						global::hscript.Expr econd1 = ( e as global::hscript.Expr_EWhile ).cond;
						this.whileLoop(econd1, e13);
						return null;
					}
					
					
					case 11:
					{
						global::hscript.Expr e14 = ( e as global::hscript.Expr_EFor ).e;
						global::hscript.Expr it = ( e as global::hscript.Expr_EFor ).it;
						string v2 = ( e as global::hscript.Expr_EFor ).v;
						this.forLoop(v2, it, e14);
						return null;
					}
					
					
					case 12:
					{
						throw ((global::System.Exception) (global::haxe.Exception.thrown(global::hscript._Interp.Stop.SBreak)) );
					}
					
					
					case 13:
					{
						throw ((global::System.Exception) (global::haxe.Exception.thrown(global::hscript._Interp.Stop.SContinue)) );
					}
					
					
					case 14:
					{
						global::hscript.CType _g3 = ( e as global::hscript.Expr_EFunction ).ret;
						string name = ( e as global::hscript.Expr_EFunction ).name;
						global::hscript.Expr fexpr = ( e as global::hscript.Expr_EFunction ).e;
						global::Array<object> params1 = ( e as global::hscript.Expr_EFunction ).args;
						global::haxe.ds.StringMap<object> capturedLocals = this.duplicate<object>(((global::haxe.ds.StringMap<object>) (this.locals) ));
						global::hscript.Interp me = this;
						bool hasOpt = false;
						int minParams = 0;
						{
							int _g4 = 0;
							while (( _g4 < params1.length )) {
								object p1 = params1[_g4];
								 ++ _g4;
								if (((global::haxe.lang.Null<object>.ofDynamic<bool>(global::haxe.lang.Runtime.getField(p1, "opt", 5545011, true)))).@value) {
									hasOpt = true;
								}
								else {
									minParams += 1;
								}
								
							}
							
						}
						
						global::haxe.lang.Function f3 = new global::hscript.Interp_expr_410__Fun(params1, name, minParams, me, fexpr, capturedLocals, _gthis);
						object f4 = global::Reflect.makeVarArgs(((global::haxe.lang.Function) (f3) ));
						if (( name != null )) {
							if (( this.depth == 0 )) {
								object __temp_expr9 = ((object) (global::haxe.lang.Runtime.callField(((global::haxe.ds.StringMap) (((object) (((global::haxe.IMap) (((object) (this.variables) )) )) )) ), "set", 5741474, new object[]{name, f4})) );
							}
							else {
								string name1 = name;
								object __temp_stmt8 = null;
								{
									object __temp_odecl3 = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(name)).@value;
									__temp_stmt8 = new global::haxe.lang.DynamicObject(new int[]{110, 5544103}, new object[]{name1, __temp_odecl3}, new int[]{}, new double[]{});
								}
								
								this.declared.push(__temp_stmt8);
								object @ref = new global::haxe.lang.DynamicObject(new int[]{114}, new object[]{f4}, new int[]{}, new double[]{});
								((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@set(name, @ref);
								capturedLocals.@set(name, @ref);
							}
							
						}
						
						return f4;
					}
					
					
					case 15:
					{
						global::hscript.Expr e15 = ( e as global::hscript.Expr_EReturn ).e;
						this.returnValue = ( (( e15 == null )) ? (null) : (this.expr(e15)) );
						throw ((global::System.Exception) (global::haxe.Exception.thrown(global::hscript._Interp.Stop.SReturn)) );
					}
					
					
					case 16:
					{
						global::hscript.Expr index = ( e as global::hscript.Expr_EArray ).index;
						global::hscript.Expr e16 = ( e as global::hscript.Expr_EArray ).e;
						object arr = this.expr(e16);
						object index1 = this.expr(index);
						if (global::Std.isOfType(arr, ((object) (typeof(global::haxe.IMap<object, object>)) ))) {
							return ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (arr) )), "get", 5144726, new object[]{index1})) );
						}
						else {
							return ((object) (global::haxe.lang.Runtime.callField(arr, "__get", 1915412854, new object[]{index1})) );
						}
						
					}
					
					
					case 17:
					{
						global::Array<object> arr1 = ( e as global::hscript.Expr_EArrayDecl ).e;
						bool tmp = default(bool);
						if (( arr1.length > 0 )) {
							global::hscript.Expr _g5 = ((global::hscript.Expr) (arr1[0]) );
							if (( _g5._hx_index == 6 )) {
								global::hscript.Expr _g6 = ( _g5 as global::hscript.Expr_EBinop ).e2;
								global::hscript.Expr _g7 = ( _g5 as global::hscript.Expr_EBinop ).e1;
								tmp = ( ( _g5 as global::hscript.Expr_EBinop ).op == "=>" );
							}
							else {
								tmp = false;
							}
							
						}
						else {
							tmp = false;
						}
						
						if (tmp) {
							bool isAllString = true;
							bool isAllInt = true;
							bool isAllObject = true;
							bool isAllEnum = true;
							global::Array keys = new global::Array<object>(new object[]{});
							global::Array values = new global::Array<object>(new object[]{});
							{
								int _g8 = 0;
								while (( _g8 < arr1.length )) {
									global::hscript.Expr e17 = ((global::hscript.Expr) (arr1[_g8]) );
									 ++ _g8;
									if (( e17._hx_index == 6 )) {
										if (( ( e17 as global::hscript.Expr_EBinop ).op == "=>" )) {
											global::hscript.Expr eValue = ( e17 as global::hscript.Expr_EBinop ).e2;
											global::hscript.Expr eKey = ( e17 as global::hscript.Expr_EBinop ).e1;
											{
												object key = this.expr(eKey);
												object @value = this.expr(eValue);
												isAllString = ( isAllString && global::Std.isOfType(key, ((object) (typeof(string)) )) );
												isAllInt = ( isAllInt && global::Std.isOfType(key, ((object) (typeof(int)) )) );
												isAllObject = ( isAllObject && global::Reflect.isObject(key) );
												isAllEnum = ( isAllEnum && global::Reflect.isEnumValue(key) );
												int __temp_expr11 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(keys, "push", 1247875546, new object[]{key}))) );
												int __temp_expr12 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(values, "push", 1247875546, new object[]{@value}))) );
											}
											
										}
										else {
											throw ((global::System.Exception) (global::haxe.Exception.thrown("=> expected")) );
										}
										
									}
									else {
										throw ((global::System.Exception) (global::haxe.Exception.thrown("=> expected")) );
									}
									
								}
								
							}
							
							object map = null;
							if (isAllInt) {
								map = new global::haxe.ds.IntMap<object>();
							}
							else if (isAllString) {
								map = new global::haxe.ds.StringMap<object>();
							}
							else if (isAllEnum) {
								map = new global::haxe.ds.EnumValueMap<object, object>();
							}
							else if (isAllObject) {
								map = new global::haxe.ds.ObjectMap<object, object>();
							}
							else {
								throw ((global::System.Exception) (global::haxe.Exception.thrown("Inconsistent key types")) );
							}
							
							{
								int _g9 = 0;
								int _g10 = ((int) (global::haxe.lang.Runtime.getField_f(keys, "length", 520590566, true)) );
								while (( _g9 < _g10 )) {
									int n1 = _g9++;
									object __temp_expr13 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (map) )), "set", 5741474, new object[]{keys[n1], values[n1]})) );
								}
								
							}
							
							return map;
						}
						else {
							global::Array a = new global::Array<object>();
							{
								int _g11 = 0;
								while (( _g11 < arr1.length )) {
									global::hscript.Expr e18 = ((global::hscript.Expr) (arr1[_g11]) );
									 ++ _g11;
									int __temp_expr10 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(a, "push", 1247875546, new object[]{this.expr(e18)}))) );
								}
								
							}
							
							return a;
						}
						
					}
					
					
					case 18:
					{
						global::Array<object> params2 = ( e as global::hscript.Expr_ENew ).@params;
						string cl = ( e as global::hscript.Expr_ENew ).cl;
						global::Array a1 = new global::Array<object>();
						{
							int _g12 = 0;
							while (( _g12 < params2.length )) {
								global::hscript.Expr e19 = ((global::hscript.Expr) (params2[_g12]) );
								 ++ _g12;
								int __temp_expr14 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(a1, "push", 1247875546, new object[]{this.expr(e19)}))) );
							}
							
						}
						
						return this.cnew(cl, a1);
					}
					
					
					case 19:
					{
						global::hscript.Expr e20 = ( e as global::hscript.Expr_EThrow ).e;
						throw ((global::System.Exception) (global::haxe.Exception.thrown(this.expr(e20))) );
					}
					
					
					case 20:
					{
						global::hscript.CType _g13 = ( e as global::hscript.Expr_ETry ).t;
						global::hscript.Expr ecatch = ( e as global::hscript.Expr_ETry ).ecatch;
						string n2 = ( e as global::hscript.Expr_ETry ).v;
						global::hscript.Expr e23 = ( e as global::hscript.Expr_ETry ).e;
						int old1 = this.declared.length;
						bool oldTry = this.inTry;
						try {
							this.inTry = true;
							object v3 = this.expr(e23);
							this.restore(old1);
							this.inTry = oldTry;
							return v3;
						}
						catch (global::System.Exception _g14){
							object _g15 = global::haxe.Exception.caught(_g14).unwrap();
							if (( _g15 is global::hscript._Interp.Stop )) {
								global::hscript._Interp.Stop err = ((global::hscript._Interp.Stop) (_g15) );
								this.inTry = oldTry;
								throw ((global::System.Exception) (global::haxe.Exception.thrown(err)) );
							}
							else {
								object err1 = _g15;
								this.restore(old1);
								this.inTry = oldTry;
								object __temp_stmt15 = null;
								{
									object __temp_odecl4 = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(n2)).@value;
									__temp_stmt15 = new global::haxe.lang.DynamicObject(new int[]{110, 5544103}, new object[]{n2, __temp_odecl4}, new int[]{}, new double[]{});
								}
								
								this.declared.push(__temp_stmt15);
								((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@set(n2, new global::haxe.lang.DynamicObject(new int[]{114}, new object[]{err1}, new int[]{}, new double[]{}));
								object v4 = this.expr(ecatch);
								this.restore(old1);
								return v4;
							}
							
						}
						
						
					}
					
					
					case 21:
					{
						global::Array<object> fl = ( e as global::hscript.Expr_EObject ).fl;
						object o = new global::haxe.lang.DynamicObject(new int[]{}, new object[]{}, new int[]{}, new double[]{});
						{
							int _g16 = 0;
							while (( _g16 < fl.length )) {
								object f5 = fl[_g16];
								 ++ _g16;
								this.@set(o, global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(f5, "name", 1224700491, true)), this.expr(((global::hscript.Expr) (global::haxe.lang.Runtime.getField(f5, "e", 101, true)) )));
							}
							
						}
						
						return o;
					}
					
					
					case 22:
					{
						global::hscript.Expr e24 = ( e as global::hscript.Expr_ETernary ).e2;
						global::hscript.Expr e110 = ( e as global::hscript.Expr_ETernary ).e1;
						global::hscript.Expr econd2 = ( e as global::hscript.Expr_ETernary ).cond;
						if (global::haxe.lang.Runtime.eq(this.expr(econd2), true)) {
							return this.expr(e110);
						}
						else {
							return this.expr(e24);
						}
						
					}
					
					
					case 23:
					{
						global::hscript.Expr def = ( e as global::hscript.Expr_ESwitch ).defaultExpr;
						global::Array<object> cases = ( e as global::hscript.Expr_ESwitch ).cases;
						global::hscript.Expr e25 = ( e as global::hscript.Expr_ESwitch ).e;
						object val = this.expr(e25);
						bool match = false;
						{
							int _g17 = 0;
							while (( _g17 < cases.length )) {
								object c1 = cases[_g17];
								 ++ _g17;
								{
									int _g18 = 0;
									global::Array<object> _g19 = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (global::haxe.lang.Runtime.getField(c1, "values", 1337394146, true)) ))) );
									while (( _g18 < _g19.length )) {
										global::hscript.Expr v5 = ((global::hscript.Expr) (_g19[_g18]) );
										 ++ _g18;
										if (global::haxe.lang.Runtime.eq(this.expr(v5), val)) {
											match = true;
											break;
										}
										
									}
									
								}
								
								if (match) {
									val = this.expr(((global::hscript.Expr) (global::haxe.lang.Runtime.getField(c1, "expr", 1126038837, true)) ));
									break;
								}
								
							}
							
						}
						
						if ( ! (match) ) {
							val = ( (( def == null )) ? (null) : (this.expr(def)) );
						}
						
						return val;
					}
					
					
					case 24:
					{
						global::hscript.Expr e26 = ( e as global::hscript.Expr_EDoWhile ).e;
						global::hscript.Expr econd3 = ( e as global::hscript.Expr_EDoWhile ).cond;
						this.doWhileLoop(econd3, e26);
						return null;
					}
					
					
					case 25:
					{
						global::Array<object> _g20 = ( e as global::hscript.Expr_EMeta ).args;
						string _g21 = ( e as global::hscript.Expr_EMeta ).name;
						global::hscript.Expr e27 = ( e as global::hscript.Expr_EMeta ).e;
						return this.expr(e27);
					}
					
					
					case 26:
					{
						global::hscript.CType _g22 = ( e as global::hscript.Expr_ECheckType ).t;
						global::hscript.Expr e28 = ( e as global::hscript.Expr_ECheckType ).e;
						return this.expr(e28);
					}
					
					
				}
				
				return null;
			}
		}
		
		
		public virtual void doWhileLoop(global::hscript.Expr econd, global::hscript.Expr e) {
			unchecked {
				int old = this.declared.length;
				while (true) {
					try {
						this.expr(e);
					}
					catch (global::System.Exception _g){
						object _g1 = global::haxe.Exception.caught(_g).unwrap();
						if (( _g1 is global::hscript._Interp.Stop )) {
							global::hscript._Interp.Stop err = ((global::hscript._Interp.Stop) (_g1) );
							switch (err._hx_index) {
								case 0:
								{
									goto label1;
								}
								
								
								case 1:
								{
									break;
								}
								
								
								case 2:
								{
									throw ((global::System.Exception) (global::haxe.Exception.thrown(err)) );
								}
								
								
							}
							
						}
						else {
							throw _g;
						}
						
					}
					
					
					if ( ! ((global::haxe.lang.Runtime.eq(this.expr(econd), true))) ) {
						break;
					}
					
				}
				label1: {};
				this.restore(old);
			}
		}
		
		
		public virtual void whileLoop(global::hscript.Expr econd, global::hscript.Expr e) {
			unchecked {
				int old = this.declared.length;
				while (global::haxe.lang.Runtime.eq(this.expr(econd), true)) {
					try {
						this.expr(e);
					}
					catch (global::System.Exception _g){
						object _g1 = global::haxe.Exception.caught(_g).unwrap();
						if (( _g1 is global::hscript._Interp.Stop )) {
							global::hscript._Interp.Stop err = ((global::hscript._Interp.Stop) (_g1) );
							switch (err._hx_index) {
								case 0:
								{
									goto label1;
								}
								
								
								case 1:
								{
									break;
								}
								
								
								case 2:
								{
									throw ((global::System.Exception) (global::haxe.Exception.thrown(err)) );
								}
								
								
							}
							
						}
						else {
							throw _g;
						}
						
					}
					
					
				}
				label1: {};
				this.restore(old);
			}
		}
		
		
		public virtual object makeIterator(object v) {
			try {
				v = ((object) (global::haxe.lang.Runtime.callField(v, "iterator", 328878574, null)) );
			}
			catch (global::System.Exception _g){
			}
			
			
			if (( ( global::haxe.lang.Runtime.getField(v, "hasNext", 407283053, true) == null ) || ( global::haxe.lang.Runtime.getField(v, "next", 1224901875, true) == null ) )) {
				global::hscript.Error e = global::hscript.Error.EInvalidIterator(global::haxe.lang.Runtime.toString(v));
				throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
			}
			
			return v;
		}
		
		
		public virtual void forLoop(string n, global::hscript.Expr it, global::hscript.Expr e) {
			unchecked {
				int old = this.declared.length;
				object __temp_stmt3 = null;
				{
					object __temp_odecl1 = (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@get(n)).@value;
					__temp_stmt3 = new global::haxe.lang.DynamicObject(new int[]{110, 5544103}, new object[]{n, __temp_odecl1}, new int[]{}, new double[]{});
				}
				
				this.declared.push(__temp_stmt3);
				object it1 = this.makeIterator(this.expr(it));
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(it1, "hasNext", 407283053, null))) {
					object __temp_stmt4 = null;
					{
						object __temp_odecl2 = ((object) (global::haxe.lang.Runtime.callField(it1, "next", 1224901875, null)) );
						__temp_stmt4 = new global::haxe.lang.DynamicObject(new int[]{114}, new object[]{__temp_odecl2}, new int[]{}, new double[]{});
					}
					
					((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.locals) )) ))) ).@set(n, __temp_stmt4);
					try {
						this.expr(e);
					}
					catch (global::System.Exception _g){
						object _g1 = global::haxe.Exception.caught(_g).unwrap();
						if (( _g1 is global::hscript._Interp.Stop )) {
							global::hscript._Interp.Stop err = ((global::hscript._Interp.Stop) (_g1) );
							switch (err._hx_index) {
								case 0:
								{
									goto label1;
								}
								
								
								case 1:
								{
									break;
								}
								
								
								case 2:
								{
									throw ((global::System.Exception) (global::haxe.Exception.thrown(err)) );
								}
								
								
							}
							
						}
						else {
							throw _g;
						}
						
					}
					
					
				}
				label1: {};
				this.restore(old);
			}
		}
		
		
		public bool isMap(object o) {
			return global::Std.isOfType(o, ((object) (typeof(global::haxe.IMap<object, object>)) ));
		}
		
		
		public object getMapValue(object map, object key) {
			return ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (map) )), "get", 5144726, new object[]{key})) );
		}
		
		
		public void setMapValue(object map, object key, object @value) {
			object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField((((global::haxe.IMap) (map) )), "set", 5741474, new object[]{key, @value})) );
		}
		
		
		public virtual object @get(object o, string f) {
			if (( o == null )) {
				global::hscript.Error e = global::hscript.Error.EInvalidAccess(f);
				throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
			}
			
			return global::Reflect.getProperty(o, f);
		}
		
		
		public virtual object @set(object o, string f, object v) {
			if (( o == null )) {
				global::hscript.Error e = global::hscript.Error.EInvalidAccess(f);
				throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
			}
			
			global::Reflect.setProperty(o, f, v);
			return v;
		}
		
		
		public virtual object fcall(object o, string f, global::Array args) {
			return this.call(o, this.@get(o, f), args);
		}
		
		
		public virtual object call(object o, object f, global::Array args) {
			return global::Reflect.callMethod(o, f, args);
		}
		
		
		public virtual object cnew(string cl, global::Array args) {
			global::System.Type c = global::Type.resolveClass(cl);
			if (global::haxe.lang.Runtime.typeEq(c, null)) {
				c = ((global::System.Type) (this.resolve(cl)) );
			}
			
			return global::Type.createInstance<object>(((global::System.Type) (c) ), ((global::Array) (args) ));
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1049971873:
					{
						this.returnValue = ((object) (@value) );
						return @value;
					}
					
					
					case 1462366467:
					{
						this.depth = ((int) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1049971873:
					{
						this.returnValue = ((object) (@value) );
						return @value;
					}
					
					
					case 1153194234:
					{
						this.declared = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (@value) ))) );
						return @value;
					}
					
					
					case 1040745046:
					{
						this.inTry = global::haxe.lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1462366467:
					{
						this.depth = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 1830181323:
					{
						this.binops = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						return @value;
					}
					
					
					case 1505719464:
					{
						this.locals = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						return @value;
					}
					
					
					case 40034999:
					{
						this.variables = ((global::haxe.ds.StringMap) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1103359965:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "cnew", 1103359965)) );
					}
					
					
					case 1102715038:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "call", 1102715038)) );
					}
					
					
					case 2090419204:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "fcall", 2090419204)) );
					}
					
					
					case 5741474:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set", 5741474)) );
					}
					
					
					case 5144726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 1499183351:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setMapValue", 1499183351)) );
					}
					
					
					case 1324265963:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "getMapValue", 1324265963)) );
					}
					
					
					case 1095840978:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "isMap", 1095840978)) );
					}
					
					
					case 1231639053:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "forLoop", 1231639053)) );
					}
					
					
					case 1483922940:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "makeIterator", 1483922940)) );
					}
					
					
					case 1637368501:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "whileLoop", 1637368501)) );
					}
					
					
					case 982974890:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "doWhileLoop", 982974890)) );
					}
					
					
					case 1126038837:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "expr", 1126038837)) );
					}
					
					
					case 1734349548:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "resolve", 1734349548)) );
					}
					
					
					case 1982509203:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "rethrow", 1982509203)) );
					}
					
					
					case 1932118984:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "error", 1932118984)) );
					}
					
					
					case 1789945678:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "restore", 1789945678)) );
					}
					
					
					case 555164043:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "duplicate", 555164043)) );
					}
					
					
					case 116222917:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "exprReturn", 116222917)) );
					}
					
					
					case 1275922997:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "execute", 1275922997)) );
					}
					
					
					case 838796847:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "increment", 838796847)) );
					}
					
					
					case 429185260:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "evalAssignOp", 429185260)) );
					}
					
					
					case 247969072:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "assignOp", 247969072)) );
					}
					
					
					case 1275479599:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "assign", 1275479599)) );
					}
					
					
					case 1267426050:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "initOps", 1267426050)) );
					}
					
					
					case 1512997393:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "posInfos", 1512997393)) );
					}
					
					
					case 1557350120:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "resetVariables", 1557350120)) );
					}
					
					
					case 1049971873:
					{
						return this.returnValue;
					}
					
					
					case 1153194234:
					{
						return this.declared;
					}
					
					
					case 1040745046:
					{
						return this.inTry;
					}
					
					
					case 1462366467:
					{
						return this.depth;
					}
					
					
					case 1830181323:
					{
						return this.binops;
					}
					
					
					case 1505719464:
					{
						return this.locals;
					}
					
					
					case 40034999:
					{
						return this.variables;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1049971873:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.returnValue)) );
					}
					
					
					case 1462366467:
					{
						return ((double) (this.depth) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1103359965:
					{
						return this.cnew(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::Array) (dynargs[1]) ));
					}
					
					
					case 1102715038:
					{
						return this.call(dynargs[0], dynargs[1], ((global::Array) (dynargs[2]) ));
					}
					
					
					case 2090419204:
					{
						return this.fcall(dynargs[0], global::haxe.lang.Runtime.toString(dynargs[1]), ((global::Array) (dynargs[2]) ));
					}
					
					
					case 5741474:
					{
						return this.@set(dynargs[0], global::haxe.lang.Runtime.toString(dynargs[1]), dynargs[2]);
					}
					
					
					case 5144726:
					{
						return this.@get(dynargs[0], global::haxe.lang.Runtime.toString(dynargs[1]));
					}
					
					
					case 1499183351:
					{
						this.setMapValue(dynargs[0], dynargs[1], dynargs[2]);
						break;
					}
					
					
					case 1324265963:
					{
						return this.getMapValue(dynargs[0], dynargs[1]);
					}
					
					
					case 1095840978:
					{
						return this.isMap(dynargs[0]);
					}
					
					
					case 1231639053:
					{
						this.forLoop(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::hscript.Expr) (dynargs[1]) ), ((global::hscript.Expr) (dynargs[2]) ));
						break;
					}
					
					
					case 1483922940:
					{
						return this.makeIterator(dynargs[0]);
					}
					
					
					case 1637368501:
					{
						this.whileLoop(((global::hscript.Expr) (dynargs[0]) ), ((global::hscript.Expr) (dynargs[1]) ));
						break;
					}
					
					
					case 982974890:
					{
						this.doWhileLoop(((global::hscript.Expr) (dynargs[0]) ), ((global::hscript.Expr) (dynargs[1]) ));
						break;
					}
					
					
					case 1126038837:
					{
						return this.expr(((global::hscript.Expr) (dynargs[0]) ));
					}
					
					
					case 1734349548:
					{
						return this.resolve(global::haxe.lang.Runtime.toString(dynargs[0]));
					}
					
					
					case 1982509203:
					{
						this.rethrow(dynargs[0]);
						break;
					}
					
					
					case 1932118984:
					{
						return this.error(((global::hscript.Error) (dynargs[0]) ), global::haxe.lang.Null<object>.ofDynamic<bool>(( (( dynargs.Length > 1 )) ? (dynargs[1]) : (null) )));
					}
					
					
					case 1789945678:
					{
						this.restore(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
						break;
					}
					
					
					case 555164043:
					{
						return this.duplicate<object>(((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (dynargs[0]) ))) ));
					}
					
					
					case 116222917:
					{
						return this.exprReturn(((global::hscript.Expr) (dynargs[0]) ));
					}
					
					
					case 1275922997:
					{
						return this.execute(((global::hscript.Expr) (dynargs[0]) ));
					}
					
					
					case 838796847:
					{
						return this.increment(((global::hscript.Expr) (dynargs[0]) ), global::haxe.lang.Runtime.toBool(dynargs[1]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ));
					}
					
					
					case 429185260:
					{
						return this.evalAssignOp(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ), ((global::hscript.Expr) (dynargs[2]) ), ((global::hscript.Expr) (dynargs[3]) ));
					}
					
					
					case 247969072:
					{
						this.assignOp(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						break;
					}
					
					
					case 1275479599:
					{
						return this.assign(((global::hscript.Expr) (dynargs[0]) ), ((global::hscript.Expr) (dynargs[1]) ));
					}
					
					
					case 1267426050:
					{
						this.initOps();
						break;
					}
					
					
					case 1512997393:
					{
						return this.posInfos();
					}
					
					
					case 1557350120:
					{
						this.resetVariables();
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			baseArr.push("returnValue");
			baseArr.push("declared");
			baseArr.push("inTry");
			baseArr.push("depth");
			baseArr.push("binops");
			baseArr.push("locals");
			baseArr.push("variables");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_resetVariables_74__Fun : global::haxe.lang.Function {
		
		public Interp_resetVariables_74__Fun(global::hscript.Interp _gthis) : base(1, 0) {
			this._gthis = _gthis;
		}
		
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			global::Array el = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array) (((object) (__fn_float1) )) )) : (((global::Array) (__fn_dyn1) )) );
			object inf = this._gthis.posInfos();
			object v = ((object) (global::haxe.lang.Runtime.callField(el, "shift", 2082663554, null)) );
			if (( ((int) (global::haxe.lang.Runtime.getField_f(el, "length", 520590566, true)) ) > 0 )) {
				global::Array __temp_expr1 = ((global::Array) (global::haxe.lang.Runtime.setField(inf, "customParams", 1830310359, el)) );
			}
			
			global::haxe.Log.trace.__hx_invoke2_o(default(double), global::Std.@string(v), default(double), inf);
			return null;
		}
		
		
		public global::hscript.Interp _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_97__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_97__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((object) (global::haxe.lang.Runtime.plus(this.me.expr(e1), this.me.expr(e2))) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_98__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_98__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e1))) ) - ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e2))) ) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_99__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_99__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e1))) ) * ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e2))) ) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_100__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_100__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e1))) ) / ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e2))) ) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_101__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_101__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e1))) ) % ((double) (global::haxe.lang.Runtime.toDouble(this.me.expr(e2))) ) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_102__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_102__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (( ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ) & ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_103__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_103__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (( ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ) | ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_104__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_104__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (( ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ) ^ ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_105__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_105__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (( ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ) << ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_106__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_106__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (( ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ) >> ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_107__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_107__Fun(global::hscript.Interp me) : base(2, 1) {
			this.me = me;
		}
		
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ((double) (((int) (( ((uint) (((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) )) ) >> ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ) )) )) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_108__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_108__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return global::haxe.lang.Runtime.eq(this.me.expr(e1), this.me.expr(e2));
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_109__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_109__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( ! (global::haxe.lang.Runtime.eq(this.me.expr(e1), this.me.expr(e2))) );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_110__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_110__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( global::haxe.lang.Runtime.compare(this.me.expr(e1), this.me.expr(e2)) >= 0 );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_111__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_111__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( global::haxe.lang.Runtime.compare(this.me.expr(e1), this.me.expr(e2)) <= 0 );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_112__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_112__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( global::haxe.lang.Runtime.compare(this.me.expr(e1), this.me.expr(e2)) > 0 );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_113__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_113__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return ( global::haxe.lang.Runtime.compare(this.me.expr(e1), this.me.expr(e2)) < 0 );
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_114__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_114__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			if (( ! (global::haxe.lang.Runtime.eq(this.me.expr(e1), true)) )) {
				return global::haxe.lang.Runtime.eq(this.me.expr(e2), true);
			}
			else {
				return true;
			}
			
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_115__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_115__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			if (global::haxe.lang.Runtime.eq(this.me.expr(e1), true)) {
				return global::haxe.lang.Runtime.eq(this.me.expr(e2), true);
			}
			else {
				return false;
			}
			
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_117__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_117__Fun(global::hscript.Interp me) : base(2, 0) {
			this.me = me;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return new global::IntIterator(((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e1))) ), ((int) (global::haxe.lang.Runtime.toInt(this.me.expr(e2))) ));
		}
		
		
		public global::hscript.Interp me;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_118__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_118__Fun() : base(2, 0) {
		}
		
		
		public static global::hscript.Interp_initOps_118__Fun __hx_current;
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			object v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float2) )) : (((object) (__fn_dyn2) )) );
			object v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			return ((object) (global::haxe.lang.Runtime.plus(v1, v2)) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_119__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_119__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_119__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			double v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float2) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn2)) )) );
			double v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float1) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn1)) )) );
			return ( v1 - v2 );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_120__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_120__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_120__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			double v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float2) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn2)) )) );
			double v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float1) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn1)) )) );
			return ( v1 * v2 );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_121__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_121__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_121__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			double v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float2) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn2)) )) );
			double v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float1) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn1)) )) );
			return ( v1 / v2 );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_122__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_122__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_122__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			double v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float2) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn2)) )) );
			double v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((double) (__fn_float1) )) : (((double) (global::haxe.lang.Runtime.toDouble(__fn_dyn1)) )) );
			return ( v1 % v2 );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_123__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_123__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_123__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (( v1 & v2 )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_124__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_124__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_124__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (( v1 | v2 )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_125__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_125__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_125__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (( v1 ^ v2 )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_126__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_126__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_126__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (( v1 << v2 )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_127__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_127__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_127__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (( v1 >> v2 )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_initOps_128__Fun : global::haxe.lang.Function {
		
		public Interp_initOps_128__Fun() : base(2, 1) {
		}
		
		
		public static global::hscript.Interp_initOps_128__Fun __hx_current;
		
		public override double __hx_invoke2_f(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			int v2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float2) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn2)) )) );
			int v1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			return ((double) (((int) (( ((uint) (v1) ) >> v2 )) )) );
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_assignOp_160__Fun : global::haxe.lang.Function {
		
		public Interp_assignOp_160__Fun(string op, global::hscript.Interp me, global::haxe.lang.Function fop) : base(2, 0) {
			this.op = op;
			this.me = me;
			this.fop = fop;
		}
		
		
		public override object __hx_invoke2_o(double __fn_float1, object __fn_dyn1, double __fn_float2, object __fn_dyn2) {
			global::hscript.Expr e2 = ( (( __fn_dyn2 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float2) )) )) : (((global::hscript.Expr) (__fn_dyn2) )) );
			global::hscript.Expr e1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::hscript.Expr) (((object) (__fn_float1) )) )) : (((global::hscript.Expr) (__fn_dyn1) )) );
			return this.me.evalAssignOp(this.op, this.fop, e1, e2);
		}
		
		
		public string op;
		
		public global::hscript.Interp me;
		
		public global::haxe.lang.Function fop;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hscript {
	public class Interp_expr_410__Fun : global::haxe.lang.Function {
		
		public Interp_expr_410__Fun(global::Array<object> params1, string name, int minParams, global::hscript.Interp me, global::hscript.Expr fexpr, global::haxe.ds.StringMap<object> capturedLocals, global::hscript.Interp _gthis) : base(1, 0) {
			this.params1 = params1;
			this.name = name;
			this.minParams = minParams;
			this.me = me;
			this.fexpr = fexpr;
			this.capturedLocals = capturedLocals;
			this._gthis = _gthis;
		}
		
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			global::Array args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array) (((object) (__fn_float1) )) )) : (((global::Array) (__fn_dyn1) )) );
			if (( (( (( args == null )) ? (0) : (((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) )) )) != this.params1.length )) {
				if (( ((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) ) < this.minParams )) {
					string str = global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Invalid number of parameters. Got ", global::haxe.lang.Runtime.toString(((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) ))), ", required "), global::haxe.lang.Runtime.toString(this.minParams));
					if (( this.name != null )) {
						str = global::haxe.lang.Runtime.concat(str, global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(" for function \'", this.name), "\'"));
					}
					
					global::hscript.Error e = global::hscript.Error.ECustom(str);
					throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
				}
				
				global::Array args2 = new global::Array<object>(new object[]{});
				int extraParams = ( ((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) ) - ((int) (this.minParams) ) );
				int pos = 0;
				{
					int _g = 0;
					while (( _g < this.params1.length )) {
						object p = this.params1[_g];
						 ++ _g;
						if (((global::haxe.lang.Null<object>.ofDynamic<bool>(global::haxe.lang.Runtime.getField(p, "opt", 5545011, true)))).@value) {
							if (( extraParams > 0 )) {
								int __temp_expr3 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(args2, "push", 1247875546, new object[]{args[pos++]}))) );
								 -- extraParams;
							}
							else {
								int __temp_expr2 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(args2, "push", 1247875546, new object[]{null}))) );
							}
							
						}
						else {
							int __temp_expr1 = ((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(args2, "push", 1247875546, new object[]{args[pos++]}))) );
						}
						
					}
					
				}
				
				args = args2;
			}
			
			global::haxe.ds.StringMap<object> old = this.me.locals;
			int depth = this.me.depth;
			this.me.depth++;
			this.me.locals = this.me.duplicate<object>(((global::haxe.ds.StringMap<object>) (this.capturedLocals) ));
			{
				int _g1 = 0;
				int _g2 = this.params1.length;
				while (( _g1 < _g2 )) {
					int i = _g1++;
					((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.me.locals) )) ))) ).@set(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(this.params1[i], "name", 1224700491, true)), new global::haxe.lang.DynamicObject(new int[]{114}, new object[]{args[i]}, new int[]{}, new double[]{}));
				}
				
			}
			
			object r = null;
			if (this._gthis.inTry) {
				try {
					r = this.me.exprReturn(this.fexpr);
				}
				catch (global::System.Exception _g3){
					object e1 = ((object) (global::haxe.Exception.caught(_g3).unwrap()) );
					this.me.locals = old;
					this.me.depth = depth;
					throw ((global::System.Exception) (global::haxe.Exception.thrown(e1)) );
				}
				
				
			}
			else {
				r = this.me.exprReturn(this.fexpr);
			}
			
			this.me.locals = old;
			this.me.depth = depth;
			return r;
		}
		
		
		public global::Array<object> params1;
		
		public string name;
		
		public int minParams;
		
		public global::hscript.Interp me;
		
		public global::hscript.Expr fexpr;
		
		public global::haxe.ds.StringMap<object> capturedLocals;
		
		public global::hscript.Interp _gthis;
		
	}
}


