// Generated by Haxe 4.1.5

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	public class BalancedTree<K, V> : global::haxe.lang.HxObject, global::haxe.ds.BalancedTree, global::haxe.IMap<K, V> {
		
		public BalancedTree(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public BalancedTree() {
			global::haxe.ds.BalancedTree<object, object>.__hx_ctor_haxe_ds_BalancedTree<K, V>(((global::haxe.ds.BalancedTree<K, V>) (this) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_BalancedTree<K_c, V_c>(global::haxe.ds.BalancedTree<K_c, V_c> __hx_this) {
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::haxe.ds.BalancedTree me) {
			return ( (( me != null )) ? (me.haxe_ds_BalancedTree_cast<K_c_c, V_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds_BalancedTree_cast<K_c, V_c>() {
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				return this;
			}
			
			global::haxe.ds.BalancedTree<K_c, V_c> new_me = new global::haxe.ds.BalancedTree<K_c, V_c>(global::haxe.lang.EmptyObject.EMPTY);
			global::Array<string> fields = global::Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public virtual object haxe_IMap_cast<K_c, V_c>() {
			return this.haxe_ds_BalancedTree_cast<K, V>();
		}
		
		
		public global::haxe.ds.TreeNode<K, V> root;
		
		public virtual void @set(K key, V @value) {
			this.root = this.setLoop(key, @value, this.root);
		}
		
		
		public virtual global::haxe.lang.Null<V> @get(K key) {
			global::haxe.ds.TreeNode<K, V> node = this.root;
			while (( node != null )) {
				int c = this.compare(key, node.key);
				if (( c == 0 )) {
					return new global::haxe.lang.Null<V>(node.@value, true);
				}
				
				if (( c < 0 )) {
					node = node.left;
				}
				else {
					node = node.right;
				}
				
			}
			
			return default(global::haxe.lang.Null<V>);
		}
		
		
		public virtual global::haxe.ds.TreeNode<K, V> setLoop(K k, V v, global::haxe.ds.TreeNode<K, V> node) {
			if (( node == null )) {
				return new global::haxe.ds.TreeNode<K, V>(null, k, v, null, default(global::haxe.lang.Null<int>));
			}
			
			int c = this.compare(k, node.key);
			if (( c == 0 )) {
				return new global::haxe.ds.TreeNode<K, V>(node.left, k, v, node.right, new global::haxe.lang.Null<int>(( (( node == null )) ? (0) : (node._height) ), true));
			}
			else if (( c < 0 )) {
				global::haxe.ds.TreeNode<K, V> nl = this.setLoop(k, v, node.left);
				return this.balance(nl, node.key, node.@value, node.right);
			}
			else {
				global::haxe.ds.TreeNode<K, V> nr = this.setLoop(k, v, node.right);
				return this.balance(node.left, node.key, node.@value, nr);
			}
			
		}
		
		
		public virtual global::haxe.ds.TreeNode<K, V> balance(global::haxe.ds.TreeNode<K, V> l, K k, V v, global::haxe.ds.TreeNode<K, V> r) {
			unchecked {
				int hl = ( (( l == null )) ? (0) : (l._height) );
				int hr = ( (( r == null )) ? (0) : (r._height) );
				if (( hl > ( hr + 2 ) )) {
					global::haxe.ds.TreeNode<K, V> _this = l.left;
					global::haxe.ds.TreeNode<K, V> _this1 = l.right;
					if (( (( (( _this == null )) ? (0) : (_this._height) )) >= (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						return new global::haxe.ds.TreeNode<K, V>(l.left, l.key, l.@value, new global::haxe.ds.TreeNode<K, V>(l.right, k, v, r, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					else {
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l.left, l.key, l.@value, l.right.left, default(global::haxe.lang.Null<int>)), l.right.key, l.right.@value, new global::haxe.ds.TreeNode<K, V>(l.right.right, k, v, r, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					
				}
				else if (( hr > ( hl + 2 ) )) {
					global::haxe.ds.TreeNode<K, V> _this2 = r.right;
					global::haxe.ds.TreeNode<K, V> _this3 = r.left;
					if (( (( (( _this2 == null )) ? (0) : (_this2._height) )) > (( (( _this3 == null )) ? (0) : (_this3._height) )) )) {
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l, k, v, r.left, default(global::haxe.lang.Null<int>)), r.key, r.@value, r.right, default(global::haxe.lang.Null<int>));
					}
					else {
						return new global::haxe.ds.TreeNode<K, V>(new global::haxe.ds.TreeNode<K, V>(l, k, v, r.left.left, default(global::haxe.lang.Null<int>)), r.left.key, r.left.@value, new global::haxe.ds.TreeNode<K, V>(r.left.right, r.key, r.@value, r.right, default(global::haxe.lang.Null<int>)), default(global::haxe.lang.Null<int>));
					}
					
				}
				else {
					return new global::haxe.ds.TreeNode<K, V>(l, k, v, r, new global::haxe.lang.Null<int>(( (( (( hl > hr )) ? (hl) : (hr) )) + 1 ), true));
				}
				
			}
		}
		
		
		public virtual int compare(K k1, K k2) {
			return global::Reflect.compare<K>(global::haxe.lang.Runtime.genericCast<K>(k1), global::haxe.lang.Runtime.genericCast<K>(k2));
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1269755426:
					{
						this.root = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 57219237:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "compare", 57219237)) );
					}
					
					
					case 596483356:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "balance", 596483356)) );
					}
					
					
					case 222029606:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "setLoop", 222029606)) );
					}
					
					
					case 5144726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 5741474:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set", 5741474)) );
					}
					
					
					case 1269755426:
					{
						return this.root;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 57219237:
					{
						return this.compare(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<K>(dynargs[1]));
					}
					
					
					case 596483356:
					{
						return this.balance(((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[0]) ))) ), global::haxe.lang.Runtime.genericCast<K>(dynargs[1]), global::haxe.lang.Runtime.genericCast<V>(dynargs[2]), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[3]) ))) ));
					}
					
					
					case 222029606:
					{
						return this.setLoop(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<V>(dynargs[1]), ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (dynargs[2]) ))) ));
					}
					
					
					case 5144726:
					{
						return (this.@get(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]))).toDynamic();
					}
					
					
					case 5741474:
					{
						this.@set(global::haxe.lang.Runtime.genericCast<K>(dynargs[0]), global::haxe.lang.Runtime.genericCast<V>(dynargs[1]));
						break;
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				return null;
			}
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			baseArr.push("root");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds.BalancedTree<object, object>))]
	public interface BalancedTree : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds_BalancedTree_cast<K_c, V_c>();
		
		object haxe_IMap_cast<K_c, V_c>();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	public class TreeNode<K, V> : global::haxe.lang.HxObject, global::haxe.ds.TreeNode {
		
		public TreeNode(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public TreeNode(global::haxe.ds.TreeNode<K, V> l, K k, V v, global::haxe.ds.TreeNode<K, V> r, global::haxe.lang.Null<int> h) {
			global::haxe.ds.TreeNode<object, object>.__hx_ctor_haxe_ds_TreeNode<K, V>(((global::haxe.ds.TreeNode<K, V>) (this) ), ((global::haxe.ds.TreeNode<K, V>) (l) ), global::haxe.lang.Runtime.genericCast<K>(k), global::haxe.lang.Runtime.genericCast<V>(v), ((global::haxe.ds.TreeNode<K, V>) (r) ), ((global::haxe.lang.Null<int>) (h) ));
		}
		
		
		protected static void __hx_ctor_haxe_ds_TreeNode<K_c, V_c>(global::haxe.ds.TreeNode<K_c, V_c> __hx_this, global::haxe.ds.TreeNode<K_c, V_c> l, K_c k, V_c v, global::haxe.ds.TreeNode<K_c, V_c> r, global::haxe.lang.Null<int> h) {
			unchecked {
				int h1 = ( ( ! (h.hasValue) ) ? (-1) : ((h).@value) );
				__hx_this.left = l;
				__hx_this.key = k;
				__hx_this.@value = v;
				__hx_this.right = r;
				if (( h1 == -1 )) {
					int tmp = default(int);
					global::haxe.ds.TreeNode<K_c, V_c> _this = __hx_this.left;
					global::haxe.ds.TreeNode<K_c, V_c> _this1 = __hx_this.right;
					if (( (( (( _this == null )) ? (0) : (_this._height) )) > (( (( _this1 == null )) ? (0) : (_this1._height) )) )) {
						global::haxe.ds.TreeNode<K_c, V_c> _this2 = __hx_this.left;
						tmp = ( (( _this2 == null )) ? (0) : (_this2._height) );
					}
					else {
						global::haxe.ds.TreeNode<K_c, V_c> _this3 = __hx_this.right;
						tmp = ( (( _this3 == null )) ? (0) : (_this3._height) );
					}
					
					__hx_this._height = ( tmp + 1 );
				}
				else {
					__hx_this._height = h1;
				}
				
			}
		}
		
		
		public static object __hx_cast<K_c_c, V_c_c>(global::haxe.ds.TreeNode me) {
			return ( (( me != null )) ? (me.haxe_ds_TreeNode_cast<K_c_c, V_c_c>()) : default(object) );
		}
		
		
		public virtual object haxe_ds_TreeNode_cast<K_c, V_c>() {
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				return this;
			}
			
			global::haxe.ds.TreeNode<K_c, V_c> new_me = new global::haxe.ds.TreeNode<K_c, V_c>(global::haxe.lang.EmptyObject.EMPTY);
			global::Array<string> fields = global::Reflect.fields(this);
			int i = 0;
			while (( i < fields.length )) {
				string field = fields[i++];
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			return new_me;
		}
		
		
		public global::haxe.ds.TreeNode<K, V> left;
		
		public global::haxe.ds.TreeNode<K, V> right;
		
		public K key;
		
		public V @value;
		
		public int _height;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						this._height = ((int) (@value) );
						return @value;
					}
					
					
					case 834174833:
					{
						this.@value = global::haxe.lang.Runtime.genericCast<V>(((object) (@value) ));
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					case 5343647:
					{
						this.key = global::haxe.lang.Runtime.genericCast<K>(((object) (@value) ));
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						this._height = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						return @value;
					}
					
					
					case 834174833:
					{
						this.@value = global::haxe.lang.Runtime.genericCast<V>(@value);
						return @value;
					}
					
					
					case 5343647:
					{
						this.key = global::haxe.lang.Runtime.genericCast<K>(@value);
						return @value;
					}
					
					
					case 1768164316:
					{
						this.right = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					case 1202718727:
					{
						this.left = ((global::haxe.ds.TreeNode<K, V>) (global::haxe.ds.TreeNode<object, object>.__hx_cast<K, V>(((global::haxe.ds.TreeNode) (@value) ))) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						return this._height;
					}
					
					
					case 834174833:
					{
						return this.@value;
					}
					
					
					case 5343647:
					{
						return this.key;
					}
					
					
					case 1768164316:
					{
						return this.right;
					}
					
					
					case 1202718727:
					{
						return this.left;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1891834246:
					{
						return ((double) (this._height) );
					}
					
					
					case 834174833:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.@value) ))) );
					}
					
					
					case 5343647:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.key) ))) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			baseArr.push("_height");
			baseArr.push("value");
			baseArr.push("key");
			baseArr.push("right");
			baseArr.push("left");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds.TreeNode<object, object>))]
	public interface TreeNode : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds_TreeNode_cast<K_c, V_c>();
		
	}
}


